"use strict";
"require baseclass";
"require ui";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_fa7db5d1266078230463ede1708aac21/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts
const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_e(e, t) {
    let { children: n, ...r } = t || {}, o = function e(t, n = []) {
        for (let r of t)null != r && "boolean" != typeof r && (Array.isArray(r) ? e(r, n) : n.push(r));
        return n;
    }(null == n ? [] : Array.isArray(n) ? n : [
        n
    ]);
    if (e === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...o), e;
    }
    if ("function" == typeof e) return e({
        ...r,
        children: o
    });
    let l = {}, f = {
        ...r
    };
    for (let [e, t] of Object.entries(f))e.startsWith("on") && "function" == typeof t ? (l[e] = t, delete f[e]) : "boolean" == typeof t && (t ? f[e] = e : delete f[e]);
    let u = Object.keys(f).length > 0 ? o.length > 1 ? E(e, f, o) : E(e, f, o[0]) : o.length > 1 ? E(e, {}, o) : E(e, {}, o[0]);
    for (let [e, t] of Object.entries(l)){
        let n = e.slice(2).toLowerCase();
        u.addEventListener(n, t);
    }
    return u;
}
function jsx(t, n) {
    return jsx_factory_e(t, n);
}
function jsxs(t, n) {
    return jsx_factory_e(t, n);
}
function jsxDEV(t, n) {
    return jsx_factory_e(t, n);
}

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_fa7db5d1266078230463ede1708aac21/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./web/resources/utils/error-tooltips.tsx

function setupErrorTooltips() {
    document.querySelectorAll(".cbi-input-invalid").forEach((t)=>{
        error_tooltips_i(t);
    }), new MutationObserver((t)=>{
        t.forEach((t)=>{
            if ("attributes" === t.type) {
                let r, n = t.target;
                "class" === t.attributeName ? n.classList.contains("cbi-input-invalid") ? error_tooltips_i(n) : (r = error_tooltips_e(n).nextElementSibling, r?.classList.contains("fluent-error-message") && r.remove()) : "data-tooltip" === t.attributeName && n.classList.contains("cbi-input-invalid") && error_tooltips_i(n);
            } else "childList" === t.type && t.addedNodes.forEach((t)=>{
                t.nodeType === Node.ELEMENT_NODE && (t.classList.contains("cbi-input-invalid") && error_tooltips_i(t), t.querySelectorAll(".cbi-input-invalid").forEach((t)=>{
                    error_tooltips_i(t);
                }));
            });
        });
    }).observe(document.body, {
        attributes: !0,
        childList: !0,
        subtree: !0,
        attributeFilter: [
            "class",
            "data-tooltip"
        ]
    });
}
function error_tooltips_e(t) {
    return t.parentElement?.closest(".control-group, .password-input, .cbi-input-group, .add-item") || t;
}
function error_tooltips_i(i) {
    let r = i.getAttribute("data-tooltip");
    if (!r) return;
    let n = error_tooltips_e(i), l = n.nextElementSibling;
    if (l?.classList.contains("fluent-error-message")) {
        let t = l.querySelector(".fluent-error-text");
        t && t.textContent !== r && (t.textContent = r), l.style.display = "";
        return;
    }
    (l = jsx("div", {
        class: "fluent-error-message",
        children: jsx("span", {
            class: "fluent-error-text",
            children: r
        })
    })).insertAdjacentHTML("afterbegin", '<svg fill="currentColor" width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg" style="flex-shrink: 0;"><path d="M6 1a5 5 0 1 0 0 10A5 5 0 0 0 6 1Zm2.12 3.28a.5.5 0 0 1 0 .7L6.7 6.42l1.41 1.41a.5.5 0 1 1-.7.7L6 7.12 4.59 8.53a.5.5 0 0 1-.7-.7L5.3 6.42 3.88 5.01a.5.5 0 0 1 .7-.7L6 5.72l1.41-1.41a.5.5 0 0 1 .71 0Z" fill="currentColor"></path></svg>'), n.parentNode?.insertBefore(l, n.nextSibling);
}

;// CONCATENATED MODULE: ./web/resources/utils/poll-pause.ts
function setupSelectionPause() {
    let t = !1;
    document.addEventListener("selectionchange", ()=>{
        let e = document.getSelection(), n = e && "" !== e.toString().trim();
        if (!n) {
            let t = document.activeElement;
            t && ("INPUT" === t.tagName || "TEXTAREA" === t.tagName) && "number" == typeof t.selectionStart && "number" == typeof t.selectionEnd && (n = t.selectionStart !== t.selectionEnd);
        }
        n ? !t && ("function" == typeof L?.poll?.active ? L.poll.active() : "function" == typeof XHR?.running && XHR.running()) && ("function" == typeof L?.poll?.stop ? L.poll.stop() : "function" == typeof XHR?.halt && XHR.halt(), t = !0) : t && ("function" == typeof L?.poll?.start ? L.poll.start() : "function" == typeof XHR?.run && XHR.run(), t = !1);
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/slide-animations.ts
const SlideAnimations = {
    durations: {
        fast: 200,
        normal: 400,
        slow: 600
    },
    runningAnimations: new WeakMap(),
    slideDown (t, i, e) {
        if (!t) return void console.warn("SlideAnimations.slideDown: No element provided");
        this.stop(t);
        let n = "string" == typeof i ? this.durations[i] || this.durations.normal : i || this.durations.normal, s = {
            display: t.style.display,
            overflow: t.style.overflow,
            height: t.style.height,
            transition: t.style.transition
        };
        t.style.display = "block", t.style.overflow = "hidden", t.style.height = "0px", t.style.transition = `height ${n}ms ease-out`, t.offsetHeight;
        let o = t.scrollHeight;
        t.style.height = `${o}px`;
        let l = ()=>{
            if (t.style.height = s.height || "", t.style.overflow = s.overflow || "", t.style.transition = s.transition || "", this.runningAnimations.delete(t), e && "function" == typeof e) try {
                e.call(t);
            } catch (t) {
                console.error("SlideAnimations callback error:", t);
            }
        }, r = setTimeout(l, n);
        this.runningAnimations.set(t, {
            timeoutId: r,
            cleanup: l
        });
    },
    slideUp (t, i, e) {
        if (!t) return void console.warn("SlideAnimations.slideUp: No element provided");
        this.stop(t);
        let n = "string" == typeof i ? this.durations[i] || this.durations.normal : i || this.durations.normal, s = {
            display: t.style.display,
            overflow: t.style.overflow,
            height: t.style.height,
            transition: t.style.transition
        }, o = t.scrollHeight;
        t.style.overflow = "hidden", t.style.height = `${o}px`, t.style.transition = `height ${n}ms ease-out`, t.offsetHeight, t.style.height = "0px";
        let l = ()=>{
            if (t.style.display = "none", t.style.height = s.height || "", t.style.overflow = s.overflow || "", t.style.transition = s.transition || "", this.runningAnimations.delete(t), e && "function" == typeof e) try {
                e.call(t);
            } catch (t) {
                console.error("SlideAnimations callback error:", t);
            }
        }, r = setTimeout(l, n);
        this.runningAnimations.set(t, {
            timeoutId: r,
            cleanup: l
        });
    },
    stop (t) {
        if (!t) return;
        let i = this.runningAnimations.get(t);
        i && (clearTimeout(i.timeoutId), i.cleanup()), t.style.transition = "", t.offsetHeight;
    },
    isAnimating (t) {
        return this.runningAnimations.has(t);
    }
};

;// CONCATENATED MODULE: ./web/resources/utils/select-dropdown.tsx
let select_dropdown_e;

let select_dropdown_n = !1, select_dropdown_r = 0;
function select_dropdown_l() {
    document.querySelectorAll(".fluent-custom-select[open]").forEach((e)=>{
        if (!(e instanceof HTMLElement) || "anchor" === e.getAttribute("data-fluent-floating")) return;
        let t = e.previousElementSibling;
        t instanceof HTMLSelectElement && select_dropdown_a(e, t);
    });
}
function setupFluentSelects() {
    "0" === document.body.getAttribute("data-theme-custom-select") || (select_dropdown_n || (select_dropdown_n = !0, window.addEventListener("scroll", select_dropdown_l, !0), window.addEventListener("resize", select_dropdown_l)), document.querySelectorAll("select").forEach((e)=>{
        select_dropdown_c(e);
    }), document.querySelectorAll("cbi-dropdown, .cbi-dropdown").forEach((e)=>{
        e.classList.contains("fluent-custom-select") || select_dropdown_i(e);
    }), new MutationObserver((e)=>{
        e.forEach((e)=>{
            e.addedNodes.forEach((e)=>{
                e.nodeType === Node.ELEMENT_NODE && ("SELECT" === e.tagName ? select_dropdown_c(e) : "CBI-DROPDOWN" === e.tagName || e.classList.contains("cbi-dropdown") ? e.classList.contains("fluent-custom-select") || select_dropdown_i(e) : (e.querySelectorAll("select").forEach((e)=>{
                    select_dropdown_c(e);
                }), e.querySelectorAll("cbi-dropdown, .cbi-dropdown").forEach((e)=>{
                    e.classList.contains("fluent-custom-select") || select_dropdown_i(e);
                })));
            });
        });
    }).observe(document.body, {
        childList: !0,
        subtree: !0
    }));
}
function select_dropdown_i(e) {
    let t;
    (t = e.querySelector("span.open")) && "true" !== t.getAttribute("data-chevron-upgraded") && (t.setAttribute("data-chevron-upgraded", "true"), t.innerHTML = '<svg fill="currentColor" class="___9ctc0p0 f1w7gpdv fez10in f1dd5bof" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M15.85 7.65c.2.2.2.5 0 .7l-5.46 5.49a.55.55 0 0 1-.78 0L4.15 8.35a.5.5 0 1 1 .7-.7L10 12.8l5.15-5.16c.2-.2.5-.2.7 0Z" fill="currentColor"></path></svg>');
}
function select_dropdown_s(e, t) {
    let o = t.offsetTop, n = o + t.offsetHeight, r = e.scrollTop, l = r + e.clientHeight;
    o < r ? e.scrollTop = o : n > l && (e.scrollTop = n - e.clientHeight);
}
function select_dropdown_a(t, o) {
    let n = t.getBoundingClientRect(), r = window.innerHeight, l = r - n.bottom, i = n.top;
    if (l < Math.min(32 * o.options.length + 10, 250) && i > l ? t.setAttribute("data-open-direction", "up") : t.setAttribute("data-open-direction", "down"), !t.closest("#modal_overlay .modal")) return void t.removeAttribute("data-fluent-floating");
    if (void 0 !== select_dropdown_e ? select_dropdown_e : select_dropdown_e = "u" > typeof CSS && "function" == typeof HTMLElement.prototype.showPopover && CSS.supports("anchor-name", "--fluent-select-anchor") && CSS.supports("position-anchor", "--fluent-select-anchor") && CSS.supports("top", "anchor(bottom)") && CSS.supports("width", "anchor-size(width)") && CSS.supports("position-try-fallbacks", "flip-block")) {
        t.setAttribute("data-fluent-floating", "anchor"), t.style.removeProperty("--fluent-dropdown-left"), t.style.removeProperty("--fluent-dropdown-top"), t.style.removeProperty("--fluent-dropdown-width"), t.style.removeProperty("--fluent-dropdown-max-height");
        return;
    }
    let s = Math.min(32 * o.options.length + 10, 350, 0.5 * r), a = l < s && i > l, d = Math.min(s, Math.max(64, a ? n.top - 8 - 4 : r - n.bottom - 8 - 4)), c = Math.min(n.width, window.innerWidth - 16), u = Math.min(Math.max(8, n.left), window.innerWidth - c - 8), p = a ? Math.max(8, n.top - d - 4) : Math.min(r - 8 - d, n.bottom + 4);
    t.setAttribute("data-open-direction", a ? "up" : "down"), t.setAttribute("data-fluent-floating", "modal"), t.style.setProperty("--fluent-dropdown-left", `${u}px`), t.style.setProperty("--fluent-dropdown-top", `${p}px`), t.style.setProperty("--fluent-dropdown-width", `${c}px`), t.style.setProperty("--fluent-dropdown-max-height", `${d}px`);
}
function select_dropdown_d(e) {
    e.removeAttribute("open"), e.removeAttribute("data-fluent-floating"), e.style.removeProperty("--fluent-dropdown-left"), e.style.removeProperty("--fluent-dropdown-top"), e.style.removeProperty("--fluent-dropdown-width"), e.style.removeProperty("--fluent-dropdown-max-height"), e.closest(".cbi-value-field, .cbi-value")?.classList.remove("cbi-dropdown-open");
    let t = e.querySelector("ul.dropdown");
    t instanceof HTMLElement && "function" == typeof t.hidePopover && t.matches(":popover-open") && t.hidePopover();
}
function select_dropdown_c(e) {
    if (e?.tagName !== "SELECT" || "true" === e.getAttribute("data-fluent-transformed") || e.closest(".cbi-dropdown") || e.multiple || function(e) {
        let t = e.getAttribute("style") || "";
        if (/\bdisplay\s*:\s*none/i.test(t) || "none" === e.style.display) return !0;
        if (!e.isConnected) return !1;
        try {
            let t = window.getComputedStyle(e);
            if ("none" === t.display) {
                let t = e.parentElement, o = !1;
                for(; t;){
                    let e = window.getComputedStyle(t);
                    if ("none" === e.display) {
                        o = !0;
                        break;
                    }
                    t = t.parentElement;
                }
                if (!o) return !0;
                let n = e.cloneNode(!1);
                n.style.display = "", document.body.appendChild(n);
                let r = window.getComputedStyle(n), l = "none" === r.display;
                return document.body.removeChild(n), l;
            }
        } catch (e) {}
        return !1;
    }(e)) return;
    let n = e.getAttribute("style");
    e.setAttribute("data-fluent-transformed", "true"), e.style.setProperty("display", "none", "important");
    let l = jsx("li", {});
    l.setAttribute("selected", "");
    let i = jsx("ul", {
        class: "dropdown"
    }), c = jsx("span", {
        class: "open"
    });
    c.innerHTML = '<svg fill="currentColor" class="___9ctc0p0 f1w7gpdv fez10in f1dd5bof" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M15.85 7.65c.2.2.2.5 0 .7l-5.46 5.49a.55.55 0 0 1-.78 0L4.15 8.35a.5.5 0 1 1 .7-.7L10 12.8l5.15-5.16c.2-.2.5-.2.7 0Z" fill="currentColor"></path></svg>';
    let u = jsxs("div", {
        class: "cbi-dropdown fluent-custom-select",
        children: [
            jsx("ul", {
                children: l
            }),
            c,
            i
        ]
    });
    if (u.setAttribute("tabindex", "0"), n) {
        let e = n.replace(/\bdisplay\s*:\s*[^;]+(;|$)/gi, "").trim();
        e && u.setAttribute("style", e);
    }
    let p = `--fluent-select-anchor-${++select_dropdown_r}`;
    u.style.setProperty("anchor-name", p), i.style.setProperty("position-anchor", p), e.disabled && (u.setAttribute("disabled", ""), u.removeAttribute("tabindex"));
    let b = ()=>{
        i.innerHTML = "";
        let o = "", n = !1;
        if (Array.from(e.options).forEach((e)=>{
            let r = jsx("li", {
                children: e.text
            });
            r.setAttribute("data-value", e.value), e.selected && (r.setAttribute("selected", ""), o = e.text, n = !0), e.disabled && r.setAttribute("disabled", ""), i.appendChild(r);
        }), !n && e.options.length > 0) {
            let t = e.options[e.selectedIndex >= 0 ? e.selectedIndex : 0];
            o = t.text;
            let n = i.querySelector(`li[data-value="${t.value}"]`);
            n?.setAttribute("selected", "");
        }
        l.textContent = o;
    };
    b(), e.parentNode?.insertBefore(u, e.nextSibling), u.addEventListener("click", (t)=>{
        if (u.hasAttribute("disabled")) return;
        let o = t.target.closest("ul.dropdown > li");
        if (o) {
            let n = o.getAttribute("data-value");
            null === n || o.hasAttribute("disabled") || (e.value = n, e.dispatchEvent(new Event("change", {
                bubbles: !0
            })), e.dispatchEvent(new Event("input", {
                bubbles: !0
            }))), select_dropdown_d(u), t.stopPropagation();
            return;
        }
        if (u.hasAttribute("open")) select_dropdown_d(u);
        else {
            document.querySelectorAll("cbi-dropdown[open], .cbi-dropdown[open]").forEach((e)=>{
                e instanceof HTMLElement && e.classList.contains("fluent-custom-select") ? select_dropdown_d(e) : (e.removeAttribute("open"), e.closest(".cbi-value-field, .cbi-value")?.classList.remove("cbi-dropdown-open"));
            }), select_dropdown_a(u, e), u.setAttribute("open", ""), u.closest(".cbi-value-field, .cbi-value")?.classList.add("cbi-dropdown-open"), "anchor" === u.getAttribute("data-fluent-floating") && (i.setAttribute("popover", "manual"), i.showPopover({
                source: u
            }));
            let t = i.querySelector("li[selected]");
            t && select_dropdown_s(i, t);
        }
        t.stopPropagation();
    });
    let f = (t)=>{
        !u.contains(t.target) && t.target !== e && u.hasAttribute("open") && select_dropdown_d(u);
    };
    document.addEventListener("click", f, !0), u.addEventListener("keydown", (t)=>{
        if (u.hasAttribute("disabled")) return;
        let o = u.hasAttribute("open"), n = Array.from(i.querySelectorAll("li:not([disabled])")), r = n.findIndex((e)=>e.hasAttribute("selected"));
        switch(t.key){
            case "Enter":
            case " ":
                if (t.preventDefault(), o) {
                    let e = n[r];
                    e && e.click();
                } else u.click();
                break;
            case "Escape":
                o && (t.preventDefault(), select_dropdown_d(u));
                break;
            case "ArrowDown":
                if (t.preventDefault(), o) {
                    if (n.length > 0) {
                        let t = (r + 1) % n.length;
                        n.forEach((o, n)=>{
                            if (n === t) {
                                o.setAttribute("selected", ""), select_dropdown_s(i, o);
                                let t = o.getAttribute("data-value");
                                null !== t && (e.value = t, e.dispatchEvent(new Event("change", {
                                    bubbles: !0
                                })), e.dispatchEvent(new Event("input", {
                                    bubbles: !0
                                })));
                            } else o.removeAttribute("selected");
                        });
                    }
                } else u.click();
                break;
            case "ArrowUp":
                if (t.preventDefault(), o) {
                    if (n.length > 0) {
                        let t = (r - 1 + n.length) % n.length;
                        n.forEach((o, n)=>{
                            if (n === t) {
                                o.setAttribute("selected", ""), select_dropdown_s(i, o);
                                let t = o.getAttribute("data-value");
                                null !== t && (e.value = t, e.dispatchEvent(new Event("change", {
                                    bubbles: !0
                                })), e.dispatchEvent(new Event("input", {
                                    bubbles: !0
                                })));
                            } else o.removeAttribute("selected");
                        });
                    }
                } else u.click();
                break;
            case "Tab":
                o && select_dropdown_d(u);
        }
    }), e.addEventListener("change", ()=>{
        let t = e.value, o = Array.from(i.querySelectorAll("li")), n = "";
        o.forEach((e)=>{
            e.getAttribute("data-value") === t ? (e.setAttribute("selected", ""), n = e.textContent || "") : e.removeAttribute("selected");
        }), l.textContent = n;
    });
    let h = new MutationObserver(()=>{
        b();
    });
    h.observe(e, {
        childList: !0
    });
    let m = new MutationObserver((t)=>{
        t.forEach((t)=>{
            "disabled" === t.attributeName && (e.disabled ? (u.setAttribute("disabled", ""), u.removeAttribute("tabindex"), select_dropdown_d(u)) : (u.removeAttribute("disabled"), u.setAttribute("tabindex", "0")));
        });
    });
    m.observe(e, {
        attributes: !0,
        attributeFilter: [
            "disabled"
        ]
    });
    let v = new MutationObserver((t)=>{
        t.forEach((t)=>{
            t.removedNodes.forEach((t)=>{
                (t === e || t.contains?.(e)) && (document.removeEventListener("click", f, !0), h.disconnect(), m.disconnect(), v.disconnect(), u.remove());
            });
        });
    });
    e.parentNode && v.observe(e.parentNode, {
        childList: !0
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/ifacebox-tooltip.ts
let ifacebox_tooltip_e = null;
function setupIfaceboxTooltips() {
    document.addEventListener("mouseover", (t)=>{
        let o = t.target.closest(".cbi-tooltip-container");
        if (!o?.closest('td[data-name="_ifacebox"] .ifacebox-body, .td[data-name="_ifacebox"] .ifacebox-body')) {
            ifacebox_tooltip_e && "none" !== ifacebox_tooltip_e.style.display && (ifacebox_tooltip_e.style.display = "none", ifacebox_tooltip_e.style.opacity = "0");
            return;
        }
        let n = o.querySelector(".cbi-tooltip");
        if (!n) return;
        ifacebox_tooltip_e || ((ifacebox_tooltip_e = document.createElement("div")).id = "fluent-global-tooltip", ifacebox_tooltip_e.className = "cbi-tooltip ifacebadge large", ifacebox_tooltip_e.style.position = "absolute", ifacebox_tooltip_e.style.zIndex = "10000", ifacebox_tooltip_e.style.pointerEvents = "none", ifacebox_tooltip_e.style.display = "none", document.body.appendChild(ifacebox_tooltip_e)), ifacebox_tooltip_e.innerHTML = n.innerHTML, ifacebox_tooltip_e.style.display = "block", ifacebox_tooltip_e.style.opacity = "0";
        let i = o.getBoundingClientRect(), l = ifacebox_tooltip_e.getBoundingClientRect(), s = window.pageYOffset + i.bottom + 6, d = window.pageXOffset + i.left + i.width / 2 - l.width / 2;
        d < 10 && (d = 10), d + l.width > window.innerWidth - 10 && (d = window.innerWidth - l.width - 10), ifacebox_tooltip_e.style.top = `${s}px`, ifacebox_tooltip_e.style.left = `${d}px`, ifacebox_tooltip_e.offsetWidth, ifacebox_tooltip_e.style.opacity = "1";
        let a = window.pageXOffset + i.left + i.width / 2 - d;
        ifacebox_tooltip_e.style.setProperty("--arrow-left", `${a}px`);
        let r = ()=>{
            ifacebox_tooltip_e && (ifacebox_tooltip_e.style.display = "none", ifacebox_tooltip_e.style.opacity = "0"), o.removeEventListener("mouseleave", r), window.removeEventListener("scroll", y, !0);
        }, y = ()=>{
            ifacebox_tooltip_e && (ifacebox_tooltip_e.style.display = "none", ifacebox_tooltip_e.style.opacity = "0"), o.removeEventListener("mouseleave", r), window.removeEventListener("scroll", y, !0);
        };
        o.addEventListener("mouseleave", r), window.addEventListener("scroll", y, !0);
    }, !0);
}

;// CONCATENATED MODULE: ./web/resources/utils/theme-features.ts
function setupThemeFeatures() {
    let e = document.body;
    if (!e) return;
    let t = L.ui, r = L.rpc.declare({
        object: 'luci.fluent',
        method: 'set_mode',
        params: [
            'mode'
        ]
    }), i = e.getAttribute('data-prefers-reduced-motion') || '1';
    if ('1' === i) {
        let t = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        e.setAttribute('data-reduce-motion', t ? 'true' : 'false');
    } else e.setAttribute('data-reduce-motion', 'false');
    '1' === i && window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change', (t)=>{
        e.setAttribute('data-reduce-motion', t.matches ? 'true' : 'false');
    });
    let l = e.getAttribute('data-theme-mode') || 'auto', s = document.getElementById('theme-toggle');
    function n(e) {
        return 'dark' === e ? 'dark' : 'light' === e ? 'light' : window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    function a(e, t) {
        s && (document.documentElement.setAttribute('data-theme', e), s.setAttribute('data-active-theme', e), s.setAttribute('data-mode', t));
    }
    s && (a(n(e.getAttribute('data-theme-mode') || 'auto'), l), s.hidden = !1, requestAnimationFrame(()=>{
        s.classList.add('visible');
    }), s.addEventListener('click', async ()=>{
        var i;
        if (s.disabled) return;
        let o = 'dark' === (i = e.getAttribute('data-theme-mode') || l) ? 'light' : 'light' === i ? 'auto' : 'dark', d = n(o);
        s.disabled = !0, a(d, o);
        try {
            let t = await r(o);
            if (t?.result !== 0) throw Error(`RPC returned ${t?.result ?? 'no response'} - permission denied or script error`);
            e.setAttribute('data-theme-mode', o);
        } catch (i) {
            let r = e.getAttribute('data-theme-mode') || l;
            a(n(r), r), t.addNotification(null, `Failed to save theme mode: ${i instanceof Error ? i.message : String(i)}`, 'error');
        } finally{
            s.disabled = !1;
        }
    }), window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (t)=>{
        if ('auto' !== (e.getAttribute('data-theme-mode') || l)) return;
        let r = t.matches ? 'dark' : 'light';
        document.documentElement.setAttribute('data-theme', r), s.setAttribute('data-active-theme', r);
    }));
    let o = '1' === e.getAttribute('data-tab-animation');
    function d(e) {
        let t = e.getBoundingClientRect();
        if (0 === t.width && 0 === t.height) return;
        let r = e.querySelector('.fluent-tab-slider');
        r || ((r = document.createElement('div')).className = 'fluent-tab-slider', e.appendChild(r));
        let i = e.querySelector('li.cbi-tab, li.active');
        if (!i) {
            r.style.width = '0px';
            return;
        }
        let l = i.querySelector('a');
        if (!l) return;
        let s = l.getBoundingClientRect(), n = window.getComputedStyle(l), a = parseFloat(n.paddingLeft) || 16, o = parseFloat(n.paddingRight) || 16, d = s.left - t.left + e.scrollLeft + a, u = s.width - a - o, c = `${d}px`, m = `${u}px`;
        if (r.style.left === c && r.style.width === m) return;
        let f = function(e) {
            if (e.classList.contains('tabs')) return 'header-tabs';
            let t = e.closest('.cbi-section');
            return t?.id ? `cbi-tabs-${t.id}` : 'cbi-tabs-generic';
        }(e), h = window._fluent_last_tab_pos?.[f];
        '' === r.style.left && h && Date.now() - h.time < 2000 && (r.style.transition = 'none', r.style.left = h.left, r.style.width = h.width, r.offsetHeight, r.style.transition = ''), r.style.left = c, r.style.width = m, window._fluent_last_tab_pos && (window._fluent_last_tab_pos[f] = {
            left: c,
            width: m,
            time: Date.now()
        });
    }
    function u() {
        document.querySelectorAll('ul.cbi-tabmenu, ul.tabs').forEach((e)=>{
            if (e.dataset.sliderInit) return void d(e);
            e.dataset.sliderInit = 'true';
            let t = e.querySelector('.fluent-tab-slider');
            if (t || ((t = document.createElement('div')).className = 'fluent-tab-slider', e.appendChild(t)), o && e.classList.contains('tabs')) {
                let r = null;
                try {
                    r = sessionStorage.getItem('fluent-tab-slider-pos');
                } catch  {}
                if (r) try {
                    let i = JSON.parse(r);
                    sessionStorage.removeItem('fluent-tab-slider-pos'), t.style.transition = 'none', t.style.left = i.left, t.style.width = i.width, t.offsetHeight, t.style.transition = '', d(e);
                } catch  {
                    d(e);
                }
                else d(e), t.style.transition = 'none', t.style.transform = 'scaleX(0)', t.offsetHeight, t.style.transition = '', t.style.transform = 'scaleX(1)';
                e.querySelectorAll('li > a').forEach((e)=>{
                    let r = e.getAttribute('href');
                    r && '#' !== r && e.addEventListener('click', ()=>{
                        try {
                            t && sessionStorage.setItem('fluent-tab-slider-pos', JSON.stringify({
                                left: t.style.left,
                                width: t.style.width
                            }));
                        } catch  {}
                    });
                });
            } else d(e);
            new MutationObserver(()=>{
                d(e);
            }).observe(e, {
                attributes: !0,
                subtree: !0,
                attributeFilter: [
                    'class'
                ]
            });
            try {
                new IntersectionObserver((t)=>{
                    for (let r of t)r.isIntersecting && d(e);
                }, {
                    threshold: 0
                }).observe(e);
            } catch (e) {
                console.warn('Fluent theme: IntersectionObserver not supported', e);
            }
        });
    }
    if (window._fluent_last_tab_pos = window._fluent_last_tab_pos || {}, u(), new MutationObserver(()=>u()).observe(e, {
        childList: !0,
        subtree: !0
    }), window.addEventListener('resize', ()=>{
        document.querySelectorAll('ul.cbi-tabmenu, ul.tabs').forEach((e)=>{
            d(e);
        });
    }), '1' === e.getAttribute('data-loading-bar')) {
        let e = !1, t = document.getElementById('fluent-top-loading'), r = ()=>{
            t && !e && t.classList.add('loaded');
        }, i = ()=>{
            t && t.classList.remove('loaded');
        };
        'interactive' === document.readyState || 'complete' === document.readyState ? r() : document.addEventListener('DOMContentLoaded', r), window.addEventListener('load', r), window.addEventListener('beforeunload', ()=>{
            e = !0, i();
        }), document.addEventListener('click', (e)=>{
            let t = e.target;
            if (!t) return;
            let r = t.closest('a');
            if (r) {
                let e = r.getAttribute('href');
                !e || e.startsWith('#') || e.startsWith("javascript:") || r.getAttribute('target') || r.hostname !== location.hostname || i();
            }
        }), document.addEventListener('submit', (e)=>{
            if (e.defaultPrevented) return;
            let t = e.target;
            if (!t) return;
            let r = t.closest('form');
            r && !r.getAttribute('target') && i();
        }), new MutationObserver(()=>{
            Array.from(document.querySelectorAll('.spinning, .loading, #view > .spinning')).some((e)=>{
                let t = window.getComputedStyle(e);
                return e.getClientRects().length > 0 && 'none' !== t.display && 'hidden' !== t.visibility && !e.closest('.btn');
            }) ? i() : r();
        }).observe(document.documentElement, {
            childList: !0,
            subtree: !0
        });
    }
    function c(e, t) {
        let r, i, l = t ? 'fluent-sidebar-parent-slider' : 'fluent-sidebar-slider', s = e.querySelector(`.${l}`);
        s || ((s = document.createElement('div')).className = l, e.appendChild(s));
        let n = e.querySelector('li.active');
        if (!n || t && (n.classList.contains('slide') || n.querySelector('.slide-menu'))) {
            s.style.height = '0px', s.style.opacity = '0';
            return;
        }
        s.style.opacity = '1';
        let a = t ? n.querySelector('a.menu, a.food') : n;
        if (!a) return;
        let o = a.getBoundingClientRect(), d = e.getBoundingClientRect();
        t ? (r = o.top - d.top + e.scrollTop + 0.2 * o.height, i = 0.6 * o.height) : (r = o.top - d.top + e.scrollTop + 0.15 * o.height, i = 0.7 * o.height), s.style.top = `${r}px`, s.style.height = `${i}px`;
    }
    function m() {
        let e = document.querySelector('#mainmenu');
        if (!e) return;
        let t = e.querySelector('ul.nav');
        if (t) {
            let e = t.querySelector('.fluent-sidebar-parent-slider');
            if (e || ((e = document.createElement('div')).className = 'fluent-sidebar-parent-slider', t.appendChild(e)), t.classList.add('has-slider'), !t.dataset.sliderInit && (t.dataset.sliderInit = 'true', o && t.querySelectorAll('li > a.menu, li > a.food').forEach((e)=>{
                let r = e.getAttribute('href');
                r && '#' !== r && e.addEventListener('click', ()=>{
                    try {
                        let e = t.querySelector('.fluent-sidebar-parent-slider');
                        e && sessionStorage.setItem('fluent-sidebar-parent-pos', JSON.stringify({
                            top: e.style.top,
                            height: e.style.height
                        }));
                    } catch  {}
                });
            })), o) {
                let t = null;
                try {
                    t = sessionStorage.getItem('fluent-sidebar-parent-pos');
                } catch  {}
                if (t) try {
                    let r = JSON.parse(t);
                    sessionStorage.removeItem('fluent-sidebar-parent-pos'), e.style.transition = 'none', e.style.top = r.top, e.style.height = r.height, e.offsetHeight, e.style.transition = '';
                } catch  {}
            }
            c(t, !0);
        }
        e.querySelectorAll('ul.slide-menu').forEach((e)=>{
            let t = e.classList.contains('active'), r = e.querySelector('.fluent-sidebar-slider');
            if (r || ((r = document.createElement('div')).className = 'fluent-sidebar-slider', e.appendChild(r)), e.classList.add('has-slider'), !e.dataset.sliderInit && (e.dataset.sliderInit = 'true', o && e.querySelectorAll('li > a').forEach((t)=>{
                let r = t.getAttribute('href');
                r && '#' !== r && t.addEventListener('click', ()=>{
                    try {
                        let t = e.querySelector('.fluent-sidebar-slider');
                        t && sessionStorage.setItem('fluent-sidebar-submenu-pos', JSON.stringify({
                            top: t.style.top,
                            height: t.style.height
                        }));
                    } catch  {}
                });
            })), o && t) {
                let e = null;
                try {
                    e = sessionStorage.getItem('fluent-sidebar-submenu-pos');
                } catch  {}
                if (e) try {
                    let t = JSON.parse(e);
                    sessionStorage.removeItem('fluent-sidebar-submenu-pos'), r.style.transition = 'none', r.style.top = t.top, r.style.height = t.height, r.offsetHeight, r.style.transition = '';
                } catch  {}
            }
            c(e, !1);
        });
    }
    m(), new MutationObserver(()=>m()).observe(e, {
        childList: !0,
        subtree: !0
    }), document.addEventListener('fluent-menu-expand', ()=>{
        let e = document.querySelector('#mainmenu');
        if (e) {
            let t = e.querySelector('ul.nav');
            t && (c(t, !0), setTimeout(()=>{
                c(t, !0);
            }, 250));
        }
    }), document.addEventListener('fluent-sidebar-state-change', ()=>{
        let e = document.querySelector('#mainmenu');
        if (e) {
            let t = e.querySelector('ul.nav');
            t && c(t, !0), e.querySelectorAll('ul.slide-menu').forEach((e)=>{
                c(e, !1);
            });
        }
    }), window.addEventListener('resize', ()=>{
        let e = document.querySelector('#mainmenu');
        if (e) {
            let t = e.querySelector('ul.nav');
            t && c(t, !0), e.querySelectorAll('ul.slide-menu').forEach((e)=>{
                c(e, !1);
            });
        }
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/menu-search.ts
function menu_search_e(e) {
    return e.toLowerCase().replace(/\s+/g, " ");
}
let menu_search_t = "fluent-menu-search";
function setupMenuSearch(n) {
    let l = [], r = (r)=>{
        let a = document.querySelector(r);
        if (!a) return;
        a.innerHTML = "";
        let { input: u } = function(n) {
            let l = document.createElement("div");
            l.className = menu_search_t;
            let r = document.createElement("input");
            r.type = "search", r.className = "fluent-menu-search-input", r.placeholder = _("Search menu\u2026"), r.autocomplete = "off", r.spellcheck = !1, r.setAttribute("aria-label", _("Search menu items"));
            let a = document.createElement("span");
            a.className = "fluent-menu-search-hotkey", a.textContent = "Ctrl+K";
            let u = document.createElement("div");
            u.className = "fluent-menu-search-overlay", u.style.display = "none", l.appendChild(r), l.appendChild(a), l.appendChild(u);
            let c = -1, i = [];
            function s() {
                u.style.display = "none", u.innerHTML = "", c = -1, i = [];
            }
            function o(e) {
                s(), r.blur(), window.location.href = L.url(e.url);
            }
            function d(e) {
                let t = u.querySelectorAll(".fluent-menu-search-item");
                0 !== t.length && (c >= 0 && t[c] && (t[c].classList.remove("selected"), t[c].removeAttribute("aria-selected")), (c += e) < 0 && (c = t.length - 1), c >= t.length && (c = 0), t[c].classList.add("selected"), t[c].setAttribute("aria-selected", "true"), t[c].scrollIntoView({
                    block: "nearest"
                }));
            }
            return r.addEventListener("input", ()=>{
                let t = r.value.trim();
                t ? function(e) {
                    if (i = e, u.innerHTML = "", c = -1, 0 === e.length) {
                        u.style.display = "none";
                        return;
                    }
                    let t = document.createElement("ul");
                    t.className = "fluent-menu-search-list", t.setAttribute("role", "listbox");
                    let n = Math.min(e.length, 20);
                    for(let l = 0; l < n; l++){
                        let n = e[l], r = document.createElement("li");
                        r.className = "fluent-menu-search-item", r.setAttribute("role", "option"), r.setAttribute("data-index", String(l));
                        let a = document.createElement("span");
                        if (a.className = "fluent-menu-search-label", a.textContent = _(n.node.title || n.node.name || ""), n.breadcrumb.length > 1) {
                            let e = document.createElement("span");
                            e.className = "fluent-menu-search-path", e.textContent = n.breadcrumb.slice(0, -1).join(" \u2192 "), r.appendChild(e);
                        }
                        r.appendChild(a), r.addEventListener("mousedown", (e)=>{
                            e.preventDefault(), o(n);
                        }), r.addEventListener("click", ()=>o(n)), t.appendChild(r);
                    }
                    if (e.length > 20) {
                        let n = document.createElement("li");
                        n.className = "fluent-menu-search-more", n.textContent = _("and {count} more\u2026").replace("{count}", String(e.length - 20)), t.appendChild(n);
                    }
                    u.appendChild(t), u.style.display = "";
                    let l = r.getBoundingClientRect();
                    u.style.left = "0", u.style.top = l.height + "px";
                }(function(t, n) {
                    let l = menu_search_e(n);
                    if (!l) return [];
                    let r = [];
                    return !function t(n, a, u) {
                        for (let c of ui.menu.getChildren(n)){
                            let n = a ? `${a}/${c.name}` : c.name, i = [
                                ...u
                            ], s = c.title || c.name || "", o = s ? _(s) : "";
                            s && i.push(o), (o && menu_search_e(o).includes(l) || s && menu_search_e(s).includes(l)) && r.push({
                                node: c,
                                url: n,
                                breadcrumb: [
                                    ...i
                                ]
                            }), t(c, n, i);
                        }
                    }(t, "", []), r;
                }(n, t)) : s();
            }), r.addEventListener("keydown", (e)=>{
                if ("Escape" === e.key) {
                    s(), r.blur();
                    return;
                }
                if ("ArrowDown" === e.key) {
                    e.preventDefault(), d(1);
                    return;
                }
                if ("ArrowUp" === e.key) {
                    e.preventDefault(), d(-1);
                    return;
                }
                if ("Enter" === e.key) {
                    e.preventDefault();
                    let t = u.querySelectorAll(".fluent-menu-search-item");
                    c >= 0 && t[c] ? t[c].click() : i.length > 0 && o(i[0]);
                    return;
                }
            }), r.addEventListener("blur", ()=>{
                setTimeout(()=>{
                    u.contains(document.activeElement) || s();
                }, 150);
            }), u.addEventListener("mousedown", (e)=>e.preventDefault()), {
                input: r,
                overlay: u
            };
        }(n);
        a.appendChild(u.closest(`.${menu_search_t}`)), l.push(u);
    };
    r(".header__search-slot"), r(".sidebar__search-slot"), 0 !== l.length && document.addEventListener("keydown", (e)=>{
        if ((e.ctrlKey || e.metaKey) && "k" === e.key || "/" === e.key && !e.ctrlKey && !e.metaKey && !e.altKey && document.activeElement?.tagName !== "INPUT" && document.activeElement?.tagName !== "TEXTAREA" && !document.activeElement?.getAttribute("contenteditable")) {
            e.preventDefault(), (()=>{
                for (let e of l)if (null !== e.offsetParent) {
                    e.focus(), e.select();
                    return;
                }
            })();
            return;
        }
        let t = l.find((e)=>document.activeElement === e);
        "Escape" === e.key && t && t.blur();
    });
}

;// CONCATENATED MODULE: ./web/resources/menu-fluent.tsx








function menu_fluent_u(e) {
    document.body.setAttribute("data-sidebar-state", e), document.dispatchEvent(new CustomEvent("fluent-sidebar-state-change"));
}
function menu_fluent_c() {
    let e = localStorage.getItem("fluent-sidebar-state");
    return "collapsed" === e || "expanded" === e ? e : "expanded";
}
function menu_fluent_p() {
    document.querySelectorAll("#mainmenu ul.nav > li > a.menu.popup-open").forEach((e)=>{
        e.classList.remove("popup-open");
    }), document.querySelectorAll("#mainmenu ul.nav > li > ul.slide-menu.popup-open").forEach((e)=>{
        e.classList.remove("popup-open"), e.style.display = "none", e.style.top = "";
    });
}
const main = baseclass.extend({
    async __init__ () {
        let e = await ui.menu.load();
        this.render(e), setupSelectionPause(), setupErrorTooltips(), setupFluentSelects(), setupIfaceboxTooltips(), setupThemeFeatures(), setupMenuSearch(e);
    },
    render (e) {
        let t = e, n = "", a = ui.menu.getChildren(e);
        for(let e = 0; e < a.length; e++)(L.env.requestpath.length ? a[e].name === L.env.requestpath[0] : 0 === e) && this.renderMainMenu(a[e], a[e].name);
        if (L.env.dispatchpath.length >= 3) {
            for(let e = 0; e < 3 && t; e++){
                let a = L.env.dispatchpath[e];
                t = t.children?.[a], n = n + (n ? "/" : "") + L.env.dispatchpath[e];
            }
            t && this.renderTabMenu(t, n);
        }
        let l = document.querySelectorAll("a.showSide"), i = document.querySelector(".darkMask"), s = document.querySelector(".sidebar-collapse-toggle"), d = ui.createHandlerFn(this, "handleSidebarToggle") ?? (()=>{
            console.warn("Fluent menu: missing sidebar toggle handler");
        }), r = ui.createHandlerFn(this, "handleDesktopSidebarToggle") ?? (()=>{
            console.warn("Fluent menu: missing desktop sidebar toggle handler");
        });
        l.forEach((e)=>{
            e.addEventListener("click", d);
        }), i && i.addEventListener("click", d), s && s.addEventListener("click", r), window.innerWidth > 768 ? menu_fluent_u(menu_fluent_c()) : document.body.setAttribute("data-sidebar-state", "expanded"), window.addEventListener("resize", ()=>{
            this.adjustBrandTextSize(), window.innerWidth > 768 ? menu_fluent_u(menu_fluent_c()) : document.body.setAttribute("data-sidebar-state", "expanded");
        }), document.addEventListener("click", (e)=>{
            if (window.innerWidth <= 768 || "collapsed" !== document.body.getAttribute("data-sidebar-state")) return;
            let t = e.target, n = document.querySelector("#mainmenu");
            t && n?.contains(t) || menu_fluent_p();
        });
    },
    handleMenuExpand (e) {
        let t = e.currentTarget;
        if (!t) return;
        let n = t.parentNode, a = t.nextElementSibling, l = window.innerWidth > 768 && "collapsed" === document.body.getAttribute("data-sidebar-state"), s = !1;
        if (document.querySelectorAll(l ? ".main .main-left .nav > li > ul.slide-menu.popup-open" : ".main .main-left .nav > li > ul.slide-menu.active").forEach((e)=>{
            s || e !== a || (s = !0), e.classList.remove("popup-open", "active"), e.previousElementSibling?.classList.remove("popup-open", "active"), SlideAnimations.stop(e), l ? (e.style.display = "none", e.style.top = "") : SlideAnimations.slideUp(e, "fast");
        }), a) {
            if (!s) {
                let e = n?.querySelector(".slide-menu");
                if (e) {
                    if (a.classList.add(l ? "popup-open" : "active"), t.classList.add(l ? "popup-open" : "active"), l) {
                        SlideAnimations.stop(e), e.style.display = "block";
                        let n = t.getBoundingClientRect(), a = e.offsetHeight, l = Math.max(8, window.innerHeight - a - 8), s = n.top - 8;
                        e.style.top = `${Math.min(l, Math.max(8, s))}px`;
                    } else e.style.top = "", SlideAnimations.slideDown(e, "fast");
                    e.querySelectorAll("li > a").forEach((e)=>{
                        e.addEventListener("click", ()=>{
                            menu_fluent_p();
                        }, {
                            once: !0
                        });
                    });
                }
                t.blur();
            }
            document.dispatchEvent(new CustomEvent("fluent-menu-expand")), e.preventDefault(), e.stopPropagation();
        }
    },
    renderMainMenu (a, l, i) {
        let s = (i || 0) + 1, d = jsx("ul", {
            class: i ? "slide-menu" : "nav"
        }), r = ui.menu.getChildren(a);
        if (0 === r.length || s > 2) return jsx(Fragment, {});
        for(let n = 0; n < r.length; n++){
            let i = r[n], o = L.env.dispatchpath[s] === i.name && L.env.dispatchpath[s - 1] === a.name, u = this.renderMainMenu(i, `${l}/${i.name}`, s), c = u.children.length > 0, p = c ? "slide" : null, m = c ? "menu" : "food";
            o && (d.classList.add("active"), p = p ? `${p} active` : "null active");
            let h = o ? `${m} active` : m, f = jsxs("li", {
                class: p ?? void 0,
                children: [
                    jsxs("a", {
                        href: L.url(l, i.name),
                        onclick: 1 === s ? ui.createHandlerFn(this, "handleMenuExpand") : null,
                        class: h,
                        "data-title": (i.title || "").replace(/ /g, "_"),
                        children: [
                            1 === s || 2 === s ? jsx("span", {
                                class: "menu-icon"
                            }) : null,
                            jsx("span", {
                                class: "menu-label",
                                children: _(i.title || "")
                            })
                        ]
                    }),
                    u
                ]
            });
            d.appendChild(f);
        }
        if (1 === s) {
            let e = document.querySelector("#mainmenu");
            e && (e.appendChild(d), e.style.display = "", this.adjustBrandTextSize());
        }
        return d;
    },
    renderTabMenu (t, a, l) {
        let i = document.querySelector("#tabmenu"), s = (l || 0) + 1, d = jsx("ul", {
            class: "tabs"
        }), r = ui.menu.getChildren(t), o = null;
        if (0 === r.length) return jsx(Fragment, {});
        for(let t = 0; t < r.length; t++){
            let n = r[t], l = L.env.dispatchpath[s + 2] === n.name, i = l ? " active" : "", u = jsx("li", {
                class: `tabmenu-item-${n.name}${i}`,
                children: jsx("a", {
                    href: L.url(a, n.name),
                    children: _(n.title || "")
                })
            });
            d.appendChild(u), l && (o = n);
        }
        if (i && (i.appendChild(d), i.style.display = "", o)) {
            let e = this.renderTabMenu(o, `${a}/${o.name}`, s);
            e.children.length > 0 && i.appendChild(e);
        }
        return d;
    },
    adjustBrandTextSize () {
        let e = document.querySelector(".sidenav-header .brand-text");
        if (e) {
            let t = e.parentElement;
            if (t) {
                let n = t.clientWidth - 32;
                if (n > 0) {
                    let t = 16;
                    for(e.style.fontSize = `${t}px`; e.scrollWidth > n && t > 9;)t -= 0.5, e.style.fontSize = `${t}px`;
                }
            }
        }
    },
    handleSidebarToggle (e) {
        let t = document.querySelectorAll("a.showSide"), n = document.querySelector("#mainmenu"), a = document.querySelector(".darkMask"), l = document.querySelector(".main-right");
        0 !== t.length && n && a && l ? Array.from(t).some((e)=>e.classList.contains("active")) ? (t.forEach((e)=>{
            e.classList.remove("active");
        }), n.classList.remove("active"), l.classList.remove("active"), a.classList.remove("active")) : (t.forEach((e)=>{
            e.classList.add("active");
        }), n.classList.add("active"), l.classList.add("active"), a.classList.add("active"), this.adjustBrandTextSize()) : console.warn("Fluent menu: sidebar toggle elements are unavailable");
    },
    handleDesktopSidebarToggle (e) {
        if (e.preventDefault(), e.stopPropagation(), window.innerWidth <= 768) return;
        let t = "collapsed" == ("collapsed" === document.body.getAttribute("data-sidebar-state") ? "collapsed" : "expanded") ? "expanded" : "collapsed";
        menu_fluent_p(), localStorage.setItem("fluent-sidebar-state", t), menu_fluent_u(t), "expanded" === t && this.adjustBrandTextSize();
    }
});


return main;