"use strict";
"require baseclass";
"require ui";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_733ea5061d64f8228fe879348d9f10be/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = n || {}, { children: l } = s, f = _object_without_properties(s, [
        "children"
    ]), i = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...i), e;
    }
    if ("function" == typeof o) return o(_object_spread_props(_object_spread({}, f), {
        children: i
    }));
    let c = {}, p = _object_spread({}, f);
    for (let [e, t] of Object.entries(p))e.startsWith("on") && "function" == typeof t ? (c[e] = t, delete p[e]) : "boolean" == typeof t && (t ? p[e] = e : delete p[e]);
    let a = Object.keys(p).length > 0 ? i.length > 1 ? E(o, p, i) : E(o, p, i[0]) : i.length > 1 ? E(o, {}, i) : E(o, {}, i[0]);
    for (let [e, t] of Object.entries(c)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_733ea5061d64f8228fe879348d9f10be/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./web/resources/utils/error-tooltips.tsx

function setupErrorTooltips() {
    document.querySelectorAll(".cbi-input-invalid").forEach((t)=>{
        error_tooltips_i(t);
    }), new MutationObserver((t)=>{
        t.forEach((t)=>{
            if ("attributes" === t.type) {
                let n, r = t.target;
                "class" === t.attributeName ? r.classList.contains("cbi-input-invalid") ? error_tooltips_i(r) : (null == (n = error_tooltips_e(r).nextElementSibling) ? void 0 : n.classList.contains("fluent-error-message")) && n.remove() : "data-tooltip" === t.attributeName && r.classList.contains("cbi-input-invalid") && error_tooltips_i(r);
            } else "childList" === t.type && t.addedNodes.forEach((t)=>{
                t.nodeType === Node.ELEMENT_NODE && (t.classList.contains("cbi-input-invalid") && error_tooltips_i(t), t.querySelectorAll(".cbi-input-invalid").forEach((t)=>{
                    error_tooltips_i(t);
                }));
            });
        });
    }).observe(document.body, {
        attributes: !0,
        childList: !0,
        subtree: !0,
        attributeFilter: [
            "class",
            "data-tooltip"
        ]
    });
}
function error_tooltips_e(t) {
    var e;
    return (null == (e = t.parentElement) ? void 0 : e.closest(".control-group, .password-input, .cbi-input-group, .add-item")) || t;
}
function error_tooltips_i(i) {
    var n;
    let r = i.getAttribute("data-tooltip");
    if (!r) return;
    let l = error_tooltips_e(i), s = l.nextElementSibling;
    if (null == s ? void 0 : s.classList.contains("fluent-error-message")) {
        let t = s.querySelector(".fluent-error-text");
        t && t.textContent !== r && (t.textContent = r), s.style.display = "";
        return;
    }
    (s = jsx("div", {
        class: "fluent-error-message",
        children: jsx("span", {
            class: "fluent-error-text",
            children: r
        })
    })).insertAdjacentHTML("afterbegin", '<svg fill="currentColor" width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg" style="flex-shrink: 0;"><path d="M6 1a5 5 0 1 0 0 10A5 5 0 0 0 6 1Zm2.12 3.28a.5.5 0 0 1 0 .7L6.7 6.42l1.41 1.41a.5.5 0 1 1-.7.7L6 7.12 4.59 8.53a.5.5 0 0 1-.7-.7L5.3 6.42 3.88 5.01a.5.5 0 0 1 .7-.7L6 5.72l1.41-1.41a.5.5 0 0 1 .71 0Z" fill="currentColor"></path></svg>'), null == (n = l.parentNode) || n.insertBefore(s, l.nextSibling);
}

;// CONCATENATED MODULE: ./web/resources/utils/poll-pause.ts
function setupSelectionPause() {
    let t = !1;
    document.addEventListener("selectionchange", ()=>{
        var n, e, l, o, i, u, c, p, a;
        let f = document.getSelection(), r = f && "" !== f.toString().trim();
        if (!r) {
            let t = document.activeElement;
            t && ("INPUT" === t.tagName || "TEXTAREA" === t.tagName) && "number" == typeof t.selectionStart && "number" == typeof t.selectionEnd && (r = t.selectionStart !== t.selectionEnd);
        }
        r ? !t && ("function" == typeof (null == (e = L) || null == (n = e.poll) ? void 0 : n.active) ? L.poll.active() : "function" == typeof (null == (l = XHR) ? void 0 : l.running) && XHR.running()) && ("function" == typeof (null == (i = L) || null == (o = i.poll) ? void 0 : o.stop) ? L.poll.stop() : "function" == typeof (null == (u = XHR) ? void 0 : u.halt) && XHR.halt(), t = !0) : t && ("function" == typeof (null == (p = L) || null == (c = p.poll) ? void 0 : c.start) ? L.poll.start() : "function" == typeof (null == (a = XHR) ? void 0 : a.run) && XHR.run(), t = !1);
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/slide-animations.ts
const SlideAnimations = {
    durations: {
        fast: 200,
        normal: 400,
        slow: 600
    },
    runningAnimations: new WeakMap(),
    slideDown (t, i, e) {
        if (!t) return void console.warn("SlideAnimations.slideDown: No element provided");
        this.stop(t);
        let n = "string" == typeof i ? this.durations[i] || this.durations.normal : i || this.durations.normal, s = {
            display: t.style.display,
            overflow: t.style.overflow,
            height: t.style.height,
            transition: t.style.transition
        };
        t.style.display = "block", t.style.overflow = "hidden", t.style.height = "0px", t.style.transition = "height ".concat(n, "ms ease-out"), t.offsetHeight;
        let o = t.scrollHeight;
        t.style.height = "".concat(o, "px");
        let l = ()=>{
            if (t.style.height = s.height || "", t.style.overflow = s.overflow || "", t.style.transition = s.transition || "", this.runningAnimations.delete(t), e && "function" == typeof e) try {
                e.call(t);
            } catch (t) {
                console.error("SlideAnimations callback error:", t);
            }
        }, r = setTimeout(l, n);
        this.runningAnimations.set(t, {
            timeoutId: r,
            cleanup: l
        });
    },
    slideUp (t, i, e) {
        if (!t) return void console.warn("SlideAnimations.slideUp: No element provided");
        this.stop(t);
        let n = "string" == typeof i ? this.durations[i] || this.durations.normal : i || this.durations.normal, s = {
            display: t.style.display,
            overflow: t.style.overflow,
            height: t.style.height,
            transition: t.style.transition
        }, o = t.scrollHeight;
        t.style.overflow = "hidden", t.style.height = "".concat(o, "px"), t.style.transition = "height ".concat(n, "ms ease-out"), t.offsetHeight, t.style.height = "0px";
        let l = ()=>{
            if (t.style.display = "none", t.style.height = s.height || "", t.style.overflow = s.overflow || "", t.style.transition = s.transition || "", this.runningAnimations.delete(t), e && "function" == typeof e) try {
                e.call(t);
            } catch (t) {
                console.error("SlideAnimations callback error:", t);
            }
        }, r = setTimeout(l, n);
        this.runningAnimations.set(t, {
            timeoutId: r,
            cleanup: l
        });
    },
    stop (t) {
        if (!t) return;
        let i = this.runningAnimations.get(t);
        i && (clearTimeout(i.timeoutId), i.cleanup()), t.style.transition = "", t.offsetHeight;
    },
    isAnimating (t) {
        return this.runningAnimations.has(t);
    }
};

;// CONCATENATED MODULE: ./web/resources/utils/select-dropdown.tsx

function setupFluentSelects() {
    "0" === document.body.getAttribute("data-theme-custom-select") || (document.querySelectorAll("select").forEach((e)=>{
        select_dropdown_r(e);
    }), document.querySelectorAll("cbi-dropdown").forEach((e)=>{
        select_dropdown_l(e);
    }), new MutationObserver((e)=>{
        e.forEach((e)=>{
            e.addedNodes.forEach((e)=>{
                e.nodeType === Node.ELEMENT_NODE && ("SELECT" === e.tagName ? select_dropdown_r(e) : "CBI-DROPDOWN" === e.tagName ? select_dropdown_l(e) : (e.querySelectorAll("select").forEach((e)=>{
                    select_dropdown_r(e);
                }), e.querySelectorAll("cbi-dropdown").forEach((e)=>{
                    select_dropdown_l(e);
                })));
            });
        });
    }).observe(document.body, {
        childList: !0,
        subtree: !0
    }));
}
function select_dropdown_l(e) {
    let t = e.querySelector("span.open");
    t && "true" !== t.getAttribute("data-chevron-upgraded") && (t.setAttribute("data-chevron-upgraded", "true"), t.innerHTML = '<svg fill="currentColor" class="___9ctc0p0 f1w7gpdv fez10in f1dd5bof" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M15.85 7.65c.2.2.2.5 0 .7l-5.46 5.49a.55.55 0 0 1-.78 0L4.15 8.35a.5.5 0 1 1 .7-.7L10 12.8l5.15-5.16c.2-.2.5-.2.7 0Z" fill="currentColor"></path></svg>');
}
function select_dropdown_r(l) {
    var r;
    if ((null == l ? void 0 : l.tagName) !== "SELECT" || "true" === l.getAttribute("data-fluent-transformed") || l.closest(".cbi-dropdown") || l.multiple || function(e) {
        let t = e.getAttribute("style") || "";
        if (/\bdisplay\s*:\s*none/i.test(t) || "none" === e.style.display) return !0;
        if (!e.isConnected) return !1;
        try {
            let t = window.getComputedStyle(e);
            if ("none" === t.display) {
                let t = e.parentElement, l = !1;
                for(; t;){
                    let e = window.getComputedStyle(t);
                    if ("none" === e.display) {
                        l = !0;
                        break;
                    }
                    t = t.parentElement;
                }
                if (!l) return !0;
                let r = e.cloneNode(!1);
                r.style.display = "", document.body.appendChild(r);
                let i = window.getComputedStyle(r), n = "none" === i.display;
                return document.body.removeChild(r), n;
            }
        } catch (e) {}
        return !1;
    }(l)) return;
    let i = l.getAttribute("style");
    l.setAttribute("data-fluent-transformed", "true"), l.style.setProperty("display", "none", "important");
    let n = jsx("li", {});
    n.setAttribute("selected", "");
    let o = jsx("ul", {
        class: "dropdown"
    }), s = jsx("span", {
        class: "open"
    });
    s.innerHTML = '<svg fill="currentColor" class="___9ctc0p0 f1w7gpdv fez10in f1dd5bof" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M15.85 7.65c.2.2.2.5 0 .7l-5.46 5.49a.55.55 0 0 1-.78 0L4.15 8.35a.5.5 0 1 1 .7-.7L10 12.8l5.15-5.16c.2-.2.5-.2.7 0Z" fill="currentColor"></path></svg>';
    let a = jsxs("div", {
        class: "cbi-dropdown fluent-custom-select",
        children: [
            jsx("ul", {
                children: n
            }),
            s,
            o
        ]
    });
    if (a.setAttribute("tabindex", "0"), i) {
        let e = i.replace(/\bdisplay\s*:\s*[^;]+(;|$)/gi, "").trim();
        e && a.setAttribute("style", e);
    }
    l.disabled && (a.setAttribute("disabled", ""), a.removeAttribute("tabindex"));
    let d = ()=>{
        o.innerHTML = "";
        let t = "", r = !1;
        if (Array.from(l.options).forEach((l)=>{
            let i = jsx("li", {
                children: l.text
            });
            i.setAttribute("data-value", l.value), l.selected && (i.setAttribute("selected", ""), t = l.text, r = !0), l.disabled && i.setAttribute("disabled", ""), o.appendChild(i);
        }), !r && l.options.length > 0) {
            let e = l.options[l.selectedIndex >= 0 ? l.selectedIndex : 0];
            t = e.text;
            let r = o.querySelector('li[data-value="'.concat(e.value, '"]'));
            null == r || r.setAttribute("selected", "");
        }
        n.textContent = t;
    };
    d(), null == (r = l.parentNode) || r.insertBefore(a, l.nextSibling), a.addEventListener("click", (e)=>{
        var t, r, i;
        if (a.hasAttribute("disabled")) return;
        let n = e.target.closest("ul.dropdown > li");
        if (n) {
            let r = n.getAttribute("data-value");
            null === r || n.hasAttribute("disabled") || (l.value = r, l.dispatchEvent(new Event("change", {
                bubbles: !0
            })), l.dispatchEvent(new Event("input", {
                bubbles: !0
            }))), a.removeAttribute("open"), null == (t = a.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open"), e.stopPropagation();
            return;
        }
        if (a.hasAttribute("open")) a.removeAttribute("open"), null == (r = a.closest(".cbi-value-field, .cbi-value")) || r.classList.remove("cbi-dropdown-open");
        else {
            document.querySelectorAll("cbi-dropdown[open], .cbi-dropdown[open]").forEach((e)=>{
                var t;
                e.removeAttribute("open"), null == (t = e.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open");
            });
            let e = a.getBoundingClientRect(), t = window.innerHeight - e.bottom, r = e.top;
            t < Math.min(32 * l.options.length + 10, 250) && r > t ? a.setAttribute("data-open-direction", "up") : a.setAttribute("data-open-direction", "down"), a.setAttribute("open", ""), null == (i = a.closest(".cbi-value-field, .cbi-value")) || i.classList.add("cbi-dropdown-open");
            let n = o.querySelector("li[selected]");
            n && n.scrollIntoView({
                block: "nearest"
            });
        }
        e.stopPropagation();
    });
    let c = (e)=>{
        if (!a.contains(e.target) && a.hasAttribute("open")) {
            var t;
            a.removeAttribute("open"), null == (t = a.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open");
        }
    };
    document.addEventListener("click", c, !0), a.addEventListener("keydown", (e)=>{
        var t, r;
        if (a.hasAttribute("disabled")) return;
        let i = a.hasAttribute("open"), n = Array.from(o.querySelectorAll("li:not([disabled])")), s = n.findIndex((e)=>e.hasAttribute("selected"));
        switch(e.key){
            case "Enter":
            case " ":
                if (e.preventDefault(), i) {
                    let e = n[s];
                    e && e.click();
                } else a.click();
                break;
            case "Escape":
                i && (e.preventDefault(), a.removeAttribute("open"), null == (t = a.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open"));
                break;
            case "ArrowDown":
                if (e.preventDefault(), i) {
                    if (n.length > 0) {
                        let e = (s + 1) % n.length;
                        n.forEach((t, r)=>{
                            if (r === e) {
                                t.setAttribute("selected", ""), t.scrollIntoView({
                                    block: "nearest"
                                });
                                let e = t.getAttribute("data-value");
                                null !== e && (l.value = e, l.dispatchEvent(new Event("change", {
                                    bubbles: !0
                                })), l.dispatchEvent(new Event("input", {
                                    bubbles: !0
                                })));
                            } else t.removeAttribute("selected");
                        });
                    }
                } else a.click();
                break;
            case "ArrowUp":
                if (e.preventDefault(), i) {
                    if (n.length > 0) {
                        let e = (s - 1 + n.length) % n.length;
                        n.forEach((t, r)=>{
                            if (r === e) {
                                t.setAttribute("selected", ""), t.scrollIntoView({
                                    block: "nearest"
                                });
                                let e = t.getAttribute("data-value");
                                null !== e && (l.value = e, l.dispatchEvent(new Event("change", {
                                    bubbles: !0
                                })), l.dispatchEvent(new Event("input", {
                                    bubbles: !0
                                })));
                            } else t.removeAttribute("selected");
                        });
                    }
                } else a.click();
                break;
            case "Tab":
                i && (a.removeAttribute("open"), null == (r = a.closest(".cbi-value-field, .cbi-value")) || r.classList.remove("cbi-dropdown-open"));
        }
    }), l.addEventListener("change", ()=>{
        let e = l.value, t = Array.from(o.querySelectorAll("li")), r = "";
        t.forEach((t)=>{
            t.getAttribute("data-value") === e ? (t.setAttribute("selected", ""), r = t.textContent || "") : t.removeAttribute("selected");
        }), n.textContent = r;
    });
    let u = new MutationObserver(()=>{
        d();
    });
    u.observe(l, {
        childList: !0
    });
    let b = new MutationObserver((e)=>{
        e.forEach((e)=>{
            if ("disabled" === e.attributeName) if (l.disabled) {
                var t;
                a.setAttribute("disabled", ""), a.removeAttribute("tabindex"), a.removeAttribute("open"), null == (t = a.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open");
            } else a.removeAttribute("disabled"), a.setAttribute("tabindex", "0");
        });
    });
    b.observe(l, {
        attributes: !0,
        attributeFilter: [
            "disabled"
        ]
    });
    let p = new MutationObserver((e)=>{
        e.forEach((e)=>{
            e.removedNodes.forEach((e)=>{
                var t;
                (e === l || (null == (t = e.contains) ? void 0 : t.call(e, l))) && (document.removeEventListener("click", c, !0), u.disconnect(), b.disconnect(), p.disconnect(), a.remove());
            });
        });
    });
    l.parentNode && p.observe(l.parentNode, {
        childList: !0
    });
}

;// CONCATENATED MODULE: ./web/resources/menu-fluent.tsx





const main = baseclass.extend({
    async __init__ () {
        let e = await ui.menu.load();
        this.render(e), setupSelectionPause(), setupErrorTooltips(), setupFluentSelects();
    },
    render (e) {
        var t, n, a;
        let l = e, i = "", r = ui.menu.getChildren(e);
        for(let e = 0; e < r.length; e++)(L.env.requestpath.length ? r[e].name === L.env.requestpath[0] : 0 === e) && this.renderMainMenu(r[e], r[e].name);
        if (L.env.dispatchpath.length >= 3) {
            for(let e = 0; e < 3 && l; e++){
                let t = L.env.dispatchpath[e];
                l = null == (a = l.children) ? void 0 : a[t], i = i + (i ? "/" : "") + L.env.dispatchpath[e];
            }
            l && this.renderTabMenu(l, i);
        }
        let s = document.querySelector("a.showSide"), d = document.querySelector(".darkMask");
        s && s.addEventListener("click", null != (t = ui.createHandlerFn(this, "handleSidebarToggle")) ? t : ()=>{
            console.warn("Sidebar toggle handler not found");
        }), d && d.addEventListener("click", null != (n = ui.createHandlerFn(this, "handleSidebarToggle")) ? n : ()=>{
            console.warn("Sidebar toggle handler not found");
        }), window.addEventListener("resize", L.bind(this.adjustBrandTextSize, this));
    },
    handleMenuExpand (e) {
        let t = e.target;
        if (!t) return;
        let n = t.parentNode, a = t.nextElementSibling, l = !1;
        if (document.querySelectorAll(".main .main-left .nav > li > ul.active").forEach((e)=>{
            var t;
            SlideAnimations.stop(e), e.classList.remove("active"), null == (t = e.previousElementSibling) || t.classList.remove("active"), SlideAnimations.slideUp(e, "fast"), l || e !== a || (l = !0);
        }), a) {
            if (!l) {
                let e = null == n ? void 0 : n.querySelector(".slide-menu");
                e && (a.classList.add("active"), t.classList.add("active"), SlideAnimations.slideDown(e, "fast")), t.blur();
            }
            e.preventDefault(), e.stopPropagation();
        }
    },
    renderMainMenu (a, l, i) {
        let r = (i || 0) + 1, s = jsx("ul", {
            class: i ? "slide-menu" : "nav"
        }), d = ui.menu.getChildren(a);
        if (0 === d.length || r > 2) return jsx(Fragment, {});
        for(let n = 0; n < d.length; n++){
            let i = d[n], c = L.env.dispatchpath[r] === i.name && L.env.dispatchpath[r - 1] === a.name, o = this.renderMainMenu(i, "".concat(l, "/").concat(i.name), r), u = o.children.length > 0, h = u ? "slide" : null, m = u ? "menu" : "food";
            c && (s.classList.add("active"), h = h ? "".concat(h, " active") : "null active");
            let p = jsxs("li", {
                class: null != h ? h : void 0,
                children: [
                    jsx("a", {
                        href: L.url(l, i.name),
                        onclick: 1 === r ? ui.createHandlerFn(this, "handleMenuExpand") : null,
                        class: m,
                        "data-title": (i.title || "").replace(/ /g, "_"),
                        children: _(i.title || "")
                    }),
                    o
                ]
            });
            s.appendChild(p);
        }
        if (1 === r) {
            let e = document.querySelector("#mainmenu");
            e && (e.appendChild(s), e.style.display = "", this.adjustBrandTextSize());
        }
        return s;
    },
    renderTabMenu (t, a, l) {
        let i = document.querySelector("#tabmenu"), r = (l || 0) + 1, s = jsx("ul", {
            class: "tabs"
        }), d = ui.menu.getChildren(t), c = null;
        if (0 === d.length) return jsx(Fragment, {});
        for(let t = 0; t < d.length; t++){
            let n = d[t], l = L.env.dispatchpath[r + 2] === n.name, i = l ? " active" : "", o = jsx("li", {
                class: _("tabmenu-item-%s %s").format(n.name, i),
                children: jsx("a", {
                    href: L.url(a, n.name),
                    children: _(n.title || "")
                })
            });
            s.appendChild(o), l && (c = n);
        }
        if (i && (i.appendChild(s), i.style.display = "", c)) {
            let e = this.renderTabMenu(c, "".concat(a, "/").concat(c.name), r);
            e.children.length > 0 && i.appendChild(e);
        }
        return s;
    },
    adjustBrandTextSize () {
        let e = document.querySelector(".sidenav-header .brand-text");
        if (e) {
            let t = e.parentElement;
            if (t) {
                let n = t.clientWidth - 32;
                if (n > 0) {
                    let t = 16;
                    for(e.style.fontSize = "".concat(t, "px"); e.scrollWidth > n && t > 9;)t -= 0.5, e.style.fontSize = "".concat(t, "px");
                }
            }
        }
    },
    handleSidebarToggle (e) {
        let t = document.querySelector("a.showSide"), n = document.querySelector("#mainmenu"), a = document.querySelector(".darkMask"), l = document.querySelector(".main-right");
        t && n && a && l ? t.classList.contains("active") ? (t.classList.remove("active"), n.classList.remove("active"), l.classList.remove("active"), a.classList.remove("active")) : (t.classList.add("active"), n.classList.add("active"), l.classList.add("active"), a.classList.add("active"), this.adjustBrandTextSize()) : console.warn("Sidebar toggle elements not found");
    }
});


return main;