"use strict";
"require baseclass";
"require ui";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_fa7db5d1266078230463ede1708aac21/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = n || {}, { children: l } = s, f = _object_without_properties(s, [
        "children"
    ]), i = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...i), e;
    }
    if ("function" == typeof o) return o(_object_spread_props(_object_spread({}, f), {
        children: i
    }));
    let c = {}, p = _object_spread({}, f);
    for (let [e, t] of Object.entries(p))e.startsWith("on") && "function" == typeof t ? (c[e] = t, delete p[e]) : "boolean" == typeof t && (t ? p[e] = e : delete p[e]);
    let a = Object.keys(p).length > 0 ? i.length > 1 ? E(o, p, i) : E(o, p, i[0]) : i.length > 1 ? E(o, {}, i) : E(o, {}, i[0]);
    for (let [e, t] of Object.entries(c)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_fa7db5d1266078230463ede1708aac21/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./web/resources/utils/error-tooltips.tsx

function setupErrorTooltips() {
    document.querySelectorAll(".cbi-input-invalid").forEach((t)=>{
        error_tooltips_i(t);
    }), new MutationObserver((t)=>{
        t.forEach((t)=>{
            if ("attributes" === t.type) {
                let n, r = t.target;
                "class" === t.attributeName ? r.classList.contains("cbi-input-invalid") ? error_tooltips_i(r) : (null == (n = error_tooltips_e(r).nextElementSibling) ? void 0 : n.classList.contains("fluent-error-message")) && n.remove() : "data-tooltip" === t.attributeName && r.classList.contains("cbi-input-invalid") && error_tooltips_i(r);
            } else "childList" === t.type && t.addedNodes.forEach((t)=>{
                t.nodeType === Node.ELEMENT_NODE && (t.classList.contains("cbi-input-invalid") && error_tooltips_i(t), t.querySelectorAll(".cbi-input-invalid").forEach((t)=>{
                    error_tooltips_i(t);
                }));
            });
        });
    }).observe(document.body, {
        attributes: !0,
        childList: !0,
        subtree: !0,
        attributeFilter: [
            "class",
            "data-tooltip"
        ]
    });
}
function error_tooltips_e(t) {
    var e;
    return (null == (e = t.parentElement) ? void 0 : e.closest(".control-group, .password-input, .cbi-input-group, .add-item")) || t;
}
function error_tooltips_i(i) {
    var n;
    let r = i.getAttribute("data-tooltip");
    if (!r) return;
    let l = error_tooltips_e(i), s = l.nextElementSibling;
    if (null == s ? void 0 : s.classList.contains("fluent-error-message")) {
        let t = s.querySelector(".fluent-error-text");
        t && t.textContent !== r && (t.textContent = r), s.style.display = "";
        return;
    }
    (s = jsx("div", {
        class: "fluent-error-message",
        children: jsx("span", {
            class: "fluent-error-text",
            children: r
        })
    })).insertAdjacentHTML("afterbegin", '<svg fill="currentColor" width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg" style="flex-shrink: 0;"><path d="M6 1a5 5 0 1 0 0 10A5 5 0 0 0 6 1Zm2.12 3.28a.5.5 0 0 1 0 .7L6.7 6.42l1.41 1.41a.5.5 0 1 1-.7.7L6 7.12 4.59 8.53a.5.5 0 0 1-.7-.7L5.3 6.42 3.88 5.01a.5.5 0 0 1 .7-.7L6 5.72l1.41-1.41a.5.5 0 0 1 .71 0Z" fill="currentColor"></path></svg>'), null == (n = l.parentNode) || n.insertBefore(s, l.nextSibling);
}

;// CONCATENATED MODULE: ./web/resources/utils/poll-pause.ts
function setupSelectionPause() {
    let t = !1;
    document.addEventListener("selectionchange", ()=>{
        var n, e, l, o, i, u, c, p, a;
        let f = document.getSelection(), r = f && "" !== f.toString().trim();
        if (!r) {
            let t = document.activeElement;
            t && ("INPUT" === t.tagName || "TEXTAREA" === t.tagName) && "number" == typeof t.selectionStart && "number" == typeof t.selectionEnd && (r = t.selectionStart !== t.selectionEnd);
        }
        r ? !t && ("function" == typeof (null == (e = L) || null == (n = e.poll) ? void 0 : n.active) ? L.poll.active() : "function" == typeof (null == (l = XHR) ? void 0 : l.running) && XHR.running()) && ("function" == typeof (null == (i = L) || null == (o = i.poll) ? void 0 : o.stop) ? L.poll.stop() : "function" == typeof (null == (u = XHR) ? void 0 : u.halt) && XHR.halt(), t = !0) : t && ("function" == typeof (null == (p = L) || null == (c = p.poll) ? void 0 : c.start) ? L.poll.start() : "function" == typeof (null == (a = XHR) ? void 0 : a.run) && XHR.run(), t = !1);
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/slide-animations.ts
const SlideAnimations = {
    durations: {
        fast: 200,
        normal: 400,
        slow: 600
    },
    runningAnimations: new WeakMap(),
    slideDown (t, i, e) {
        if (!t) return void console.warn("SlideAnimations.slideDown: No element provided");
        this.stop(t);
        let n = "string" == typeof i ? this.durations[i] || this.durations.normal : i || this.durations.normal, s = {
            display: t.style.display,
            overflow: t.style.overflow,
            height: t.style.height,
            transition: t.style.transition
        };
        t.style.display = "block", t.style.overflow = "hidden", t.style.height = "0px", t.style.transition = "height ".concat(n, "ms ease-out"), t.offsetHeight;
        let o = t.scrollHeight;
        t.style.height = "".concat(o, "px");
        let l = ()=>{
            if (t.style.height = s.height || "", t.style.overflow = s.overflow || "", t.style.transition = s.transition || "", this.runningAnimations.delete(t), e && "function" == typeof e) try {
                e.call(t);
            } catch (t) {
                console.error("SlideAnimations callback error:", t);
            }
        }, r = setTimeout(l, n);
        this.runningAnimations.set(t, {
            timeoutId: r,
            cleanup: l
        });
    },
    slideUp (t, i, e) {
        if (!t) return void console.warn("SlideAnimations.slideUp: No element provided");
        this.stop(t);
        let n = "string" == typeof i ? this.durations[i] || this.durations.normal : i || this.durations.normal, s = {
            display: t.style.display,
            overflow: t.style.overflow,
            height: t.style.height,
            transition: t.style.transition
        }, o = t.scrollHeight;
        t.style.overflow = "hidden", t.style.height = "".concat(o, "px"), t.style.transition = "height ".concat(n, "ms ease-out"), t.offsetHeight, t.style.height = "0px";
        let l = ()=>{
            if (t.style.display = "none", t.style.height = s.height || "", t.style.overflow = s.overflow || "", t.style.transition = s.transition || "", this.runningAnimations.delete(t), e && "function" == typeof e) try {
                e.call(t);
            } catch (t) {
                console.error("SlideAnimations callback error:", t);
            }
        }, r = setTimeout(l, n);
        this.runningAnimations.set(t, {
            timeoutId: r,
            cleanup: l
        });
    },
    stop (t) {
        if (!t) return;
        let i = this.runningAnimations.get(t);
        i && (clearTimeout(i.timeoutId), i.cleanup()), t.style.transition = "", t.offsetHeight;
    },
    isAnimating (t) {
        return this.runningAnimations.has(t);
    }
};

;// CONCATENATED MODULE: ./web/resources/utils/select-dropdown.tsx
let select_dropdown_e;

let select_dropdown_n = !1, select_dropdown_l = 0;
function select_dropdown_r() {
    document.querySelectorAll(".fluent-custom-select[open]").forEach((e)=>{
        if (!(e instanceof HTMLElement) || "anchor" === e.getAttribute("data-fluent-floating")) return;
        let t = e.previousElementSibling;
        t instanceof HTMLSelectElement && select_dropdown_d(e, t);
    });
}
function setupFluentSelects() {
    "0" === document.body.getAttribute("data-theme-custom-select") || (select_dropdown_n || (select_dropdown_n = !0, window.addEventListener("scroll", select_dropdown_r, !0), window.addEventListener("resize", select_dropdown_r)), document.querySelectorAll("select").forEach((e)=>{
        select_dropdown_u(e);
    }), document.querySelectorAll("cbi-dropdown, .cbi-dropdown").forEach((e)=>{
        e.classList.contains("fluent-custom-select") || select_dropdown_s(e);
    }), new MutationObserver((e)=>{
        e.forEach((e)=>{
            e.addedNodes.forEach((e)=>{
                e.nodeType === Node.ELEMENT_NODE && ("SELECT" === e.tagName ? select_dropdown_u(e) : "CBI-DROPDOWN" === e.tagName || e.classList.contains("cbi-dropdown") ? e.classList.contains("fluent-custom-select") || select_dropdown_s(e) : (e.querySelectorAll("select").forEach((e)=>{
                    select_dropdown_u(e);
                }), e.querySelectorAll("cbi-dropdown, .cbi-dropdown").forEach((e)=>{
                    e.classList.contains("fluent-custom-select") || select_dropdown_s(e);
                })));
            });
        });
    }).observe(document.body, {
        childList: !0,
        subtree: !0
    }));
}
let select_dropdown_i = 0;
function select_dropdown_s(e) {
    let t;
    if ((t = e.querySelector("span.open")) && "true" !== t.getAttribute("data-chevron-upgraded") && (t.setAttribute("data-chevron-upgraded", "true"), t.innerHTML = '<svg fill="currentColor" class="___9ctc0p0 f1w7gpdv fez10in f1dd5bof" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M15.85 7.65c.2.2.2.5 0 .7l-5.46 5.49a.55.55 0 0 1-.78 0L4.15 8.35a.5.5 0 1 1 .7-.7L10 12.8l5.15-5.16c.2-.2.5-.2.7 0Z" fill="currentColor"></path></svg>'), "true" !== e.getAttribute("data-fluent-anchor-setup")) {
        e.setAttribute("data-fluent-anchor-setup", "true");
        let t = ++select_dropdown_i, o = "--fluent-cbi-anchor-".concat(t);
        e.style.setProperty("anchor-name", o);
        let n = e.querySelector("ul.dropdown");
        n instanceof HTMLElement && n.style.setProperty("position-anchor", o);
    }
}
function select_dropdown_a(e, t) {
    let o = t.offsetTop, n = o + t.offsetHeight, l = e.scrollTop, r = l + e.clientHeight;
    o < l ? e.scrollTop = o : n > r && (e.scrollTop = n - e.clientHeight);
}
function select_dropdown_d(t, o) {
    let n = t.getBoundingClientRect(), l = window.innerHeight, r = l - n.bottom, i = n.top;
    if (r < Math.min(32 * o.options.length + 10, 250) && i > r ? t.setAttribute("data-open-direction", "up") : t.setAttribute("data-open-direction", "down"), !t.closest("#modal_overlay .modal")) return void t.removeAttribute("data-fluent-floating");
    if (void 0 !== select_dropdown_e ? select_dropdown_e : select_dropdown_e = "u" > typeof CSS && "function" == typeof HTMLElement.prototype.showPopover && CSS.supports("anchor-name", "--fluent-select-anchor") && CSS.supports("position-anchor", "--fluent-select-anchor") && CSS.supports("top", "anchor(bottom)") && CSS.supports("width", "anchor-size(width)") && CSS.supports("position-try-fallbacks", "flip-block")) {
        t.setAttribute("data-fluent-floating", "anchor"), t.style.removeProperty("--fluent-dropdown-left"), t.style.removeProperty("--fluent-dropdown-top"), t.style.removeProperty("--fluent-dropdown-width"), t.style.removeProperty("--fluent-dropdown-max-height");
        return;
    }
    let s = Math.min(32 * o.options.length + 10, 350, 0.5 * l), a = r < s && i > r, d = Math.min(s, Math.max(64, a ? n.top - 8 - 4 : l - n.bottom - 8 - 4)), c = Math.min(n.width, window.innerWidth - 16), u = Math.min(Math.max(8, n.left), window.innerWidth - c - 8), p = a ? Math.max(8, n.top - d - 4) : Math.min(l - 8 - d, n.bottom + 4);
    t.setAttribute("data-open-direction", a ? "up" : "down"), t.setAttribute("data-fluent-floating", "modal"), t.style.setProperty("--fluent-dropdown-left", "".concat(u, "px")), t.style.setProperty("--fluent-dropdown-top", "".concat(p, "px")), t.style.setProperty("--fluent-dropdown-width", "".concat(c, "px")), t.style.setProperty("--fluent-dropdown-max-height", "".concat(d, "px"));
}
function select_dropdown_c(e) {
    var t;
    e.removeAttribute("open"), e.removeAttribute("data-fluent-floating"), e.style.removeProperty("--fluent-dropdown-left"), e.style.removeProperty("--fluent-dropdown-top"), e.style.removeProperty("--fluent-dropdown-width"), e.style.removeProperty("--fluent-dropdown-max-height"), null == (t = e.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open");
    let o = e.querySelector("ul.dropdown");
    o instanceof HTMLElement && "function" == typeof o.hidePopover && o.matches(":popover-open") && o.hidePopover();
}
function select_dropdown_u(e) {
    var n;
    if ((null == e ? void 0 : e.tagName) !== "SELECT" || "true" === e.getAttribute("data-fluent-transformed") || e.closest(".cbi-dropdown") || e.multiple || function(e) {
        let t = e.getAttribute("style") || "";
        if (/\bdisplay\s*:\s*none/i.test(t) || "none" === e.style.display) return !0;
        if (!e.isConnected) return !1;
        try {
            let t = window.getComputedStyle(e);
            if ("none" === t.display) {
                let t = e.parentElement, o = !1;
                for(; t;){
                    let e = window.getComputedStyle(t);
                    if ("none" === e.display) {
                        o = !0;
                        break;
                    }
                    t = t.parentElement;
                }
                if (!o) return !0;
                let n = e.cloneNode(!1);
                n.style.display = "", document.body.appendChild(n);
                let l = window.getComputedStyle(n), r = "none" === l.display;
                return document.body.removeChild(n), r;
            }
        } catch (e) {}
        return !1;
    }(e)) return;
    let r = e.getAttribute("style");
    e.setAttribute("data-fluent-transformed", "true"), e.style.setProperty("display", "none", "important");
    let i = jsx("li", {});
    i.setAttribute("selected", "");
    let s = jsx("ul", {
        class: "dropdown"
    }), u = jsx("span", {
        class: "open"
    });
    u.innerHTML = '<svg fill="currentColor" class="___9ctc0p0 f1w7gpdv fez10in f1dd5bof" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M15.85 7.65c.2.2.2.5 0 .7l-5.46 5.49a.55.55 0 0 1-.78 0L4.15 8.35a.5.5 0 1 1 .7-.7L10 12.8l5.15-5.16c.2-.2.5-.2.7 0Z" fill="currentColor"></path></svg>';
    let p = jsxs("div", {
        class: "cbi-dropdown fluent-custom-select",
        children: [
            jsx("ul", {
                children: i
            }),
            u,
            s
        ]
    });
    if (p.setAttribute("tabindex", "0"), r) {
        let e = r.replace(/\bdisplay\s*:\s*[^;]+(;|$)/gi, "").trim();
        e && p.setAttribute("style", e);
    }
    let b = "--fluent-select-anchor-".concat(++select_dropdown_l);
    p.style.setProperty("anchor-name", b), s.style.setProperty("position-anchor", b), e.disabled && (p.setAttribute("disabled", ""), p.removeAttribute("tabindex"));
    let f = ()=>{
        s.innerHTML = "";
        let o = "", n = !1;
        if (Array.from(e.options).forEach((e)=>{
            let l = jsx("li", {
                children: e.text
            });
            l.setAttribute("data-value", e.value), e.selected && (l.setAttribute("selected", ""), o = e.text, n = !0), e.disabled && l.setAttribute("disabled", ""), s.appendChild(l);
        }), !n && e.options.length > 0) {
            let t = e.options[e.selectedIndex >= 0 ? e.selectedIndex : 0];
            o = t.text;
            let n = s.querySelector('li[data-value="'.concat(t.value, '"]'));
            null == n || n.setAttribute("selected", "");
        }
        i.textContent = o;
    };
    f(), null == (n = e.parentNode) || n.insertBefore(p, e.nextSibling), p.addEventListener("click", (t)=>{
        if (p.hasAttribute("disabled")) return;
        let o = t.target.closest("ul.dropdown > li");
        if (o) {
            let n = o.getAttribute("data-value");
            null === n || o.hasAttribute("disabled") || (e.value = n, e.dispatchEvent(new Event("change", {
                bubbles: !0
            })), e.dispatchEvent(new Event("input", {
                bubbles: !0
            }))), select_dropdown_c(p), t.stopPropagation();
            return;
        }
        if (p.hasAttribute("open")) select_dropdown_c(p);
        else {
            var n;
            document.querySelectorAll("cbi-dropdown[open], .cbi-dropdown[open]").forEach((e)=>{
                if (e instanceof HTMLElement && e.classList.contains("fluent-custom-select")) select_dropdown_c(e);
                else {
                    var t;
                    e.removeAttribute("open"), null == (t = e.closest(".cbi-value-field, .cbi-value")) || t.classList.remove("cbi-dropdown-open");
                }
            }), select_dropdown_d(p, e), p.setAttribute("open", ""), null == (n = p.closest(".cbi-value-field, .cbi-value")) || n.classList.add("cbi-dropdown-open"), "anchor" === p.getAttribute("data-fluent-floating") && (s.setAttribute("popover", "manual"), s.showPopover({
                source: p
            }));
            let t = s.querySelector("li[selected]");
            t && select_dropdown_a(s, t);
        }
        t.stopPropagation();
    });
    let h = (t)=>{
        !p.contains(t.target) && t.target !== e && p.hasAttribute("open") && select_dropdown_c(p);
    };
    document.addEventListener("click", h, !0), p.addEventListener("keydown", (t)=>{
        if (p.hasAttribute("disabled")) return;
        let o = p.hasAttribute("open"), n = Array.from(s.querySelectorAll("li:not([disabled])")), l = n.findIndex((e)=>e.hasAttribute("selected"));
        switch(t.key){
            case "Enter":
            case " ":
                if (t.preventDefault(), o) {
                    let e = n[l];
                    e && e.click();
                } else p.click();
                break;
            case "Escape":
                o && (t.preventDefault(), select_dropdown_c(p));
                break;
            case "ArrowDown":
                if (t.preventDefault(), o) {
                    if (n.length > 0) {
                        let t = (l + 1) % n.length;
                        n.forEach((o, n)=>{
                            if (n === t) {
                                o.setAttribute("selected", ""), select_dropdown_a(s, o);
                                let t = o.getAttribute("data-value");
                                null !== t && (e.value = t, e.dispatchEvent(new Event("change", {
                                    bubbles: !0
                                })), e.dispatchEvent(new Event("input", {
                                    bubbles: !0
                                })));
                            } else o.removeAttribute("selected");
                        });
                    }
                } else p.click();
                break;
            case "ArrowUp":
                if (t.preventDefault(), o) {
                    if (n.length > 0) {
                        let t = (l - 1 + n.length) % n.length;
                        n.forEach((o, n)=>{
                            if (n === t) {
                                o.setAttribute("selected", ""), select_dropdown_a(s, o);
                                let t = o.getAttribute("data-value");
                                null !== t && (e.value = t, e.dispatchEvent(new Event("change", {
                                    bubbles: !0
                                })), e.dispatchEvent(new Event("input", {
                                    bubbles: !0
                                })));
                            } else o.removeAttribute("selected");
                        });
                    }
                } else p.click();
                break;
            case "Tab":
                o && select_dropdown_c(p);
        }
    }), e.addEventListener("change", ()=>{
        let t = e.value, o = Array.from(s.querySelectorAll("li")), n = "";
        o.forEach((e)=>{
            e.getAttribute("data-value") === t ? (e.setAttribute("selected", ""), n = e.textContent || "") : e.removeAttribute("selected");
        }), i.textContent = n;
    });
    let v = new MutationObserver(()=>{
        f();
    });
    v.observe(e, {
        childList: !0
    });
    let m = new MutationObserver((t)=>{
        t.forEach((t)=>{
            "disabled" === t.attributeName && (e.disabled ? (p.setAttribute("disabled", ""), p.removeAttribute("tabindex"), select_dropdown_c(p)) : (p.removeAttribute("disabled"), p.setAttribute("tabindex", "0")));
        });
    });
    m.observe(e, {
        attributes: !0,
        attributeFilter: [
            "disabled"
        ]
    });
    let w = new MutationObserver((t)=>{
        t.forEach((t)=>{
            t.removedNodes.forEach((t)=>{
                var o;
                (t === e || (null == (o = t.contains) ? void 0 : o.call(t, e))) && (document.removeEventListener("click", h, !0), v.disconnect(), m.disconnect(), w.disconnect(), p.remove());
            });
        });
    });
    e.parentNode && w.observe(e.parentNode, {
        childList: !0
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/ifacebox-tooltip.ts
let ifacebox_tooltip_e = null;
function setupIfaceboxTooltips() {
    document.addEventListener("mouseover", (t)=>{
        let o = t.target.closest(".cbi-tooltip-container");
        if (!(null == o ? void 0 : o.closest('td[data-name="_ifacebox"] .ifacebox-body, .td[data-name="_ifacebox"] .ifacebox-body'))) {
            ifacebox_tooltip_e && "none" !== ifacebox_tooltip_e.style.display && (ifacebox_tooltip_e.style.display = "none", ifacebox_tooltip_e.style.opacity = "0");
            return;
        }
        let n = o.querySelector(".cbi-tooltip");
        if (!n) return;
        ifacebox_tooltip_e || ((ifacebox_tooltip_e = document.createElement("div")).id = "fluent-global-tooltip", ifacebox_tooltip_e.className = "cbi-tooltip ifacebadge large", ifacebox_tooltip_e.style.position = "absolute", ifacebox_tooltip_e.style.zIndex = "10000", ifacebox_tooltip_e.style.pointerEvents = "none", ifacebox_tooltip_e.style.display = "none", document.body.appendChild(ifacebox_tooltip_e)), ifacebox_tooltip_e.innerHTML = n.innerHTML, ifacebox_tooltip_e.style.display = "block", ifacebox_tooltip_e.style.opacity = "0";
        let i = o.getBoundingClientRect(), l = ifacebox_tooltip_e.getBoundingClientRect(), s = window.pageYOffset + i.bottom + 6, d = window.pageXOffset + i.left + i.width / 2 - l.width / 2;
        d < 10 && (d = 10), d + l.width > window.innerWidth - 10 && (d = window.innerWidth - l.width - 10), ifacebox_tooltip_e.style.top = "".concat(s, "px"), ifacebox_tooltip_e.style.left = "".concat(d, "px"), ifacebox_tooltip_e.offsetWidth, ifacebox_tooltip_e.style.opacity = "1";
        let a = window.pageXOffset + i.left + i.width / 2 - d;
        ifacebox_tooltip_e.style.setProperty("--arrow-left", "".concat(a, "px"));
        let c = ()=>{
            ifacebox_tooltip_e && (ifacebox_tooltip_e.style.display = "none", ifacebox_tooltip_e.style.opacity = "0"), o.removeEventListener("mouseleave", c), window.removeEventListener("scroll", r, !0);
        }, r = ()=>{
            ifacebox_tooltip_e && (ifacebox_tooltip_e.style.display = "none", ifacebox_tooltip_e.style.opacity = "0"), o.removeEventListener("mouseleave", c), window.removeEventListener("scroll", r, !0);
        };
        o.addEventListener("mouseleave", c), window.addEventListener("scroll", r, !0);
    }, !0);
}

;// CONCATENATED MODULE: ./web/resources/utils/theme-features.ts
function setupThemeFeatures() {
    let e = document.body;
    if (!e) return;
    let t = L.ui, r = L.rpc.declare({
        object: 'luci.fluent',
        method: 'set_mode',
        params: [
            'mode'
        ]
    }), i = e.getAttribute('data-prefers-reduced-motion') || '1';
    if ('1' === i) {
        let t = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        e.setAttribute('data-reduce-motion', t ? 'true' : 'false');
    } else e.setAttribute('data-reduce-motion', 'false');
    '1' === i && window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change', (t)=>{
        e.setAttribute('data-reduce-motion', t.matches ? 'true' : 'false');
    });
    let n = e.getAttribute('data-theme-mode') || 'auto', l = document.getElementById('theme-toggle');
    function s(e) {
        return 'dark' === e ? 'dark' : 'light' === e ? 'light' : window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    function a(e, t) {
        l && (document.documentElement.setAttribute('data-theme', e), l.setAttribute('data-active-theme', e), l.setAttribute('data-mode', t));
    }
    l && (a(s(e.getAttribute('data-theme-mode') || 'auto'), n), l.hidden = !1, requestAnimationFrame(()=>{
        l.classList.add('visible');
    }), l.addEventListener('click', async ()=>{
        var i, o;
        if (l.disabled) return;
        let d = 'dark' === (i = e.getAttribute('data-theme-mode') || n) ? 'light' : 'light' === i ? 'auto' : 'dark', u = s(d);
        l.disabled = !0, a(u, d);
        try {
            let t = await r(d);
            if ((null == t ? void 0 : t.result) !== 0) throw Error("RPC returned ".concat(null != (o = null == t ? void 0 : t.result) ? o : 'no response', " - permission denied or script error"));
            e.setAttribute('data-theme-mode', d);
        } catch (i) {
            let r = e.getAttribute('data-theme-mode') || n;
            a(s(r), r), t.addNotification(null, "Failed to save theme mode: ".concat(i instanceof Error ? i.message : String(i)), 'error');
        } finally{
            l.disabled = !1;
        }
    }), window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (t)=>{
        if ('auto' !== (e.getAttribute('data-theme-mode') || n)) return;
        let r = t.matches ? 'dark' : 'light';
        document.documentElement.setAttribute('data-theme', r), l.setAttribute('data-active-theme', r);
    }));
    let o = '1' === e.getAttribute('data-tab-animation');
    function d(e) {
        var t;
        let r = e.getBoundingClientRect();
        if (0 === r.width && 0 === r.height) return;
        let i = e.querySelector('.fluent-tab-slider');
        i || ((i = document.createElement('div')).className = 'fluent-tab-slider', e.appendChild(i));
        let n = e.querySelector('li.cbi-tab, li.active');
        if (!n) {
            i.style.width = '0px';
            return;
        }
        let l = n.querySelector('a');
        if (!l) return;
        let s = l.getBoundingClientRect(), a = window.getComputedStyle(l), o = parseFloat(a.paddingLeft) || 16, d = parseFloat(a.paddingRight) || 16, u = s.left - r.left + e.scrollLeft + o, c = s.width - o - d, m = "".concat(u, "px"), f = "".concat(c, "px");
        if (i.style.left === m && i.style.width === f) return;
        let h = function(e) {
            if (e.classList.contains('tabs')) return 'header-tabs';
            let t = e.closest('.cbi-section');
            return (null == t ? void 0 : t.id) ? "cbi-tabs-".concat(t.id) : 'cbi-tabs-generic';
        }(e), b = null == (t = window._fluent_last_tab_pos) ? void 0 : t[h];
        '' === i.style.left && b && Date.now() - b.time < 2000 && (i.style.transition = 'none', i.style.left = b.left, i.style.width = b.width, i.offsetHeight, i.style.transition = ''), i.style.left = m, i.style.width = f, window._fluent_last_tab_pos && (window._fluent_last_tab_pos[h] = {
            left: m,
            width: f,
            time: Date.now()
        });
    }
    function u() {
        document.querySelectorAll('ul.cbi-tabmenu, ul.tabs').forEach((e)=>{
            if (e.dataset.sliderInit) return void d(e);
            e.dataset.sliderInit = 'true';
            let t = e.querySelector('.fluent-tab-slider');
            if (t || ((t = document.createElement('div')).className = 'fluent-tab-slider', e.appendChild(t)), o && e.classList.contains('tabs')) {
                let r = null;
                try {
                    r = sessionStorage.getItem('fluent-tab-slider-pos');
                } catch (e) {}
                if (r) try {
                    let i = JSON.parse(r);
                    sessionStorage.removeItem('fluent-tab-slider-pos'), t.style.transition = 'none', t.style.left = i.left, t.style.width = i.width, t.offsetHeight, t.style.transition = '', d(e);
                } catch (t) {
                    d(e);
                }
                else d(e), t.style.transition = 'none', t.style.transform = 'scaleX(0)', t.offsetHeight, t.style.transition = '', t.style.transform = 'scaleX(1)';
                e.querySelectorAll('li > a').forEach((e)=>{
                    let r = e.getAttribute('href');
                    r && '#' !== r && e.addEventListener('click', ()=>{
                        try {
                            t && sessionStorage.setItem('fluent-tab-slider-pos', JSON.stringify({
                                left: t.style.left,
                                width: t.style.width
                            }));
                        } catch (e) {}
                    });
                });
            } else d(e);
            new MutationObserver(()=>{
                d(e);
            }).observe(e, {
                attributes: !0,
                subtree: !0,
                attributeFilter: [
                    'class'
                ]
            });
            try {
                new IntersectionObserver((t)=>{
                    for (let r of t)r.isIntersecting && d(e);
                }, {
                    threshold: 0
                }).observe(e);
            } catch (e) {
                console.warn('Fluent theme: IntersectionObserver not supported', e);
            }
        });
    }
    if (window._fluent_last_tab_pos = window._fluent_last_tab_pos || {}, u(), new MutationObserver(()=>u()).observe(e, {
        childList: !0,
        subtree: !0
    }), window.addEventListener('resize', ()=>{
        document.querySelectorAll('ul.cbi-tabmenu, ul.tabs').forEach((e)=>{
            d(e);
        });
    }), '1' === e.getAttribute('data-loading-bar')) {
        let e = !1, t = document.getElementById('fluent-top-loading'), r = ()=>{
            t && !e && t.classList.add('loaded');
        }, i = ()=>{
            t && t.classList.remove('loaded');
        };
        'interactive' === document.readyState || 'complete' === document.readyState ? r() : document.addEventListener('DOMContentLoaded', r), window.addEventListener('load', r), window.addEventListener('beforeunload', ()=>{
            e = !0, i();
        }), document.addEventListener('click', (e)=>{
            let t = e.target;
            if (!t) return;
            let r = t.closest('a');
            if (r) {
                let e = r.getAttribute('href');
                !e || e.startsWith('#') || e.startsWith("javascript:") || r.getAttribute('target') || r.hostname !== location.hostname || i();
            }
        }), document.addEventListener('submit', (e)=>{
            if (e.defaultPrevented) return;
            let t = e.target;
            if (!t) return;
            let r = t.closest('form');
            r && !r.getAttribute('target') && i();
        }), new MutationObserver(()=>{
            null !== document.querySelector('.spinning, .loading, #view > .spinning') ? i() : r();
        }).observe(document.documentElement, {
            childList: !0,
            subtree: !0
        });
    }
    function c(e, t) {
        let r, i, n = t ? 'fluent-sidebar-parent-slider' : 'fluent-sidebar-slider', l = e.querySelector(".".concat(n));
        l || ((l = document.createElement('div')).className = n, e.appendChild(l));
        let s = e.querySelector('li.active');
        if (!s || t && (s.classList.contains('slide') || s.querySelector('.slide-menu'))) {
            l.style.height = '0px', l.style.opacity = '0';
            return;
        }
        l.style.opacity = '1';
        let a = t ? s.querySelector('a.menu, a.food') : s;
        if (!a) return;
        let o = a.getBoundingClientRect(), d = e.getBoundingClientRect();
        t ? (r = o.top - d.top + e.scrollTop + 0.2 * o.height, i = 0.6 * o.height) : (r = o.top - d.top + e.scrollTop + 0.15 * o.height, i = 0.7 * o.height), l.style.top = "".concat(r, "px"), l.style.height = "".concat(i, "px");
    }
    function m() {
        let e = document.querySelector('#mainmenu');
        if (!e) return;
        let t = e.querySelector('ul.nav');
        if (t) {
            let e = t.querySelector('.fluent-sidebar-parent-slider');
            if (e || ((e = document.createElement('div')).className = 'fluent-sidebar-parent-slider', t.appendChild(e)), t.classList.add('has-slider'), !t.dataset.sliderInit && (t.dataset.sliderInit = 'true', o && t.querySelectorAll('li > a.menu, li > a.food').forEach((e)=>{
                let r = e.getAttribute('href');
                r && '#' !== r && e.addEventListener('click', ()=>{
                    try {
                        let e = t.querySelector('.fluent-sidebar-parent-slider');
                        e && sessionStorage.setItem('fluent-sidebar-parent-pos', JSON.stringify({
                            top: e.style.top,
                            height: e.style.height
                        }));
                    } catch (e) {}
                });
            })), o) {
                let t = null;
                try {
                    t = sessionStorage.getItem('fluent-sidebar-parent-pos');
                } catch (e) {}
                if (t) try {
                    let r = JSON.parse(t);
                    sessionStorage.removeItem('fluent-sidebar-parent-pos'), e.style.transition = 'none', e.style.top = r.top, e.style.height = r.height, e.offsetHeight, e.style.transition = '';
                } catch (e) {}
            }
            c(t, !0);
        }
        e.querySelectorAll('ul.slide-menu').forEach((e)=>{
            let t = e.classList.contains('active'), r = e.querySelector('.fluent-sidebar-slider');
            if (r || ((r = document.createElement('div')).className = 'fluent-sidebar-slider', e.appendChild(r)), e.classList.add('has-slider'), !e.dataset.sliderInit && (e.dataset.sliderInit = 'true', o && e.querySelectorAll('li > a').forEach((t)=>{
                let r = t.getAttribute('href');
                r && '#' !== r && t.addEventListener('click', ()=>{
                    try {
                        let t = e.querySelector('.fluent-sidebar-slider');
                        t && sessionStorage.setItem('fluent-sidebar-submenu-pos', JSON.stringify({
                            top: t.style.top,
                            height: t.style.height
                        }));
                    } catch (e) {}
                });
            })), o && t) {
                let e = null;
                try {
                    e = sessionStorage.getItem('fluent-sidebar-submenu-pos');
                } catch (e) {}
                if (e) try {
                    let t = JSON.parse(e);
                    sessionStorage.removeItem('fluent-sidebar-submenu-pos'), r.style.transition = 'none', r.style.top = t.top, r.style.height = t.height, r.offsetHeight, r.style.transition = '';
                } catch (e) {}
            }
            c(e, !1);
        });
    }
    m(), new MutationObserver(()=>m()).observe(e, {
        childList: !0,
        subtree: !0
    }), document.addEventListener('fluent-menu-expand', ()=>{
        let e = document.querySelector('#mainmenu');
        if (e) {
            let t = e.querySelector('ul.nav');
            t && (c(t, !0), setTimeout(()=>{
                c(t, !0);
            }, 250));
        }
    }), document.addEventListener('fluent-sidebar-state-change', ()=>{
        let e = document.querySelector('#mainmenu');
        if (e) {
            let t = e.querySelector('ul.nav');
            t && c(t, !0), e.querySelectorAll('ul.slide-menu').forEach((e)=>{
                c(e, !1);
            });
        }
    }), window.addEventListener('resize', ()=>{
        let e = document.querySelector('#mainmenu');
        if (e) {
            let t = e.querySelector('ul.nav');
            t && c(t, !0), e.querySelectorAll('ul.slide-menu').forEach((e)=>{
                c(e, !1);
            });
        }
    });
}

;// CONCATENATED MODULE: ./web/resources/utils/menu-search.ts
function menu_search_e(e) {
    return e.toLowerCase().replace(/\s+/g, " ");
}
let menu_search_t = "fluent-menu-search";
function setupMenuSearch(n) {
    let l = [], r = (r)=>{
        let a = document.querySelector(r);
        if (!a) return;
        a.innerHTML = "";
        let { input: u } = function(n) {
            let l = document.createElement("div");
            l.className = menu_search_t;
            let r = document.createElement("input");
            r.type = "search", r.className = "fluent-menu-search-input", r.placeholder = _("Search menu\u2026"), r.autocomplete = "off", r.spellcheck = !1, r.setAttribute("aria-label", _("Search menu items"));
            let a = document.createElement("span");
            a.className = "fluent-menu-search-hotkey", a.textContent = "Ctrl+K";
            let u = document.createElement("div");
            u.className = "fluent-menu-search-overlay", u.style.display = "none", l.appendChild(r), l.appendChild(a), l.appendChild(u);
            let c = -1, i = [];
            function s() {
                u.style.display = "none", u.innerHTML = "", c = -1, i = [];
            }
            function o(e) {
                s(), r.blur(), window.location.href = L.url(e.url);
            }
            function d(e) {
                let t = u.querySelectorAll(".fluent-menu-search-item");
                0 !== t.length && (c >= 0 && t[c] && (t[c].classList.remove("selected"), t[c].removeAttribute("aria-selected")), (c += e) < 0 && (c = t.length - 1), c >= t.length && (c = 0), t[c].classList.add("selected"), t[c].setAttribute("aria-selected", "true"), t[c].scrollIntoView({
                    block: "nearest"
                }));
            }
            return r.addEventListener("input", ()=>{
                let t = r.value.trim();
                t ? function(e) {
                    if (i = e, u.innerHTML = "", c = -1, 0 === e.length) {
                        u.style.display = "none";
                        return;
                    }
                    let t = document.createElement("ul");
                    t.className = "fluent-menu-search-list", t.setAttribute("role", "listbox");
                    let n = Math.min(e.length, 20);
                    for(let l = 0; l < n; l++){
                        let n = e[l], r = document.createElement("li");
                        r.className = "fluent-menu-search-item", r.setAttribute("role", "option"), r.setAttribute("data-index", String(l));
                        let a = document.createElement("span");
                        if (a.className = "fluent-menu-search-label", a.textContent = _(n.node.title || n.node.name || ""), n.breadcrumb.length > 1) {
                            let e = document.createElement("span");
                            e.className = "fluent-menu-search-path", e.textContent = n.breadcrumb.slice(0, -1).join(" \u2192 "), r.appendChild(e);
                        }
                        r.appendChild(a), r.addEventListener("mousedown", (e)=>{
                            e.preventDefault(), o(n);
                        }), r.addEventListener("click", ()=>o(n)), t.appendChild(r);
                    }
                    if (e.length > 20) {
                        let n = document.createElement("li");
                        n.className = "fluent-menu-search-more", n.textContent = _("and {count} more\u2026").replace("{count}", String(e.length - 20)), t.appendChild(n);
                    }
                    u.appendChild(t), u.style.display = "";
                    let l = r.getBoundingClientRect();
                    u.style.left = "0", u.style.top = l.height + "px";
                }(function(t, n) {
                    let l = menu_search_e(n);
                    if (!l) return [];
                    let r = [];
                    return !function t(n, a, u) {
                        for (let c of ui.menu.getChildren(n)){
                            let n = a ? "".concat(a, "/").concat(c.name) : c.name, i = [
                                ...u
                            ], s = c.title || c.name || "", o = s ? _(s) : "";
                            s && i.push(o), (o && menu_search_e(o).includes(l) || s && menu_search_e(s).includes(l)) && r.push({
                                node: c,
                                url: n,
                                breadcrumb: [
                                    ...i
                                ]
                            }), t(c, n, i);
                        }
                    }(t, "", []), r;
                }(n, t)) : s();
            }), r.addEventListener("keydown", (e)=>{
                if ("Escape" === e.key) {
                    s(), r.blur();
                    return;
                }
                if ("ArrowDown" === e.key) {
                    e.preventDefault(), d(1);
                    return;
                }
                if ("ArrowUp" === e.key) {
                    e.preventDefault(), d(-1);
                    return;
                }
                if ("Enter" === e.key) {
                    e.preventDefault();
                    let t = u.querySelectorAll(".fluent-menu-search-item");
                    c >= 0 && t[c] ? t[c].click() : i.length > 0 && o(i[0]);
                    return;
                }
            }), r.addEventListener("blur", ()=>{
                setTimeout(()=>{
                    u.contains(document.activeElement) || s();
                }, 150);
            }), u.addEventListener("mousedown", (e)=>e.preventDefault()), {
                input: r,
                overlay: u
            };
        }(n);
        a.appendChild(u.closest(".".concat(menu_search_t))), l.push(u);
    };
    r(".header__search-slot"), r(".sidebar__search-slot"), 0 !== l.length && document.addEventListener("keydown", (e)=>{
        var t, n, r;
        if ((e.ctrlKey || e.metaKey) && "k" === e.key || "/" === e.key && !e.ctrlKey && !e.metaKey && !e.altKey && (null == (t = document.activeElement) ? void 0 : t.tagName) !== "INPUT" && (null == (n = document.activeElement) ? void 0 : n.tagName) !== "TEXTAREA" && !(null == (r = document.activeElement) ? void 0 : r.getAttribute("contenteditable"))) {
            e.preventDefault(), (()=>{
                for (let e of l)if (null !== e.offsetParent) {
                    e.focus(), e.select();
                    return;
                }
            })();
            return;
        }
        let a = l.find((e)=>document.activeElement === e);
        "Escape" === e.key && a && a.blur();
    });
}

;// CONCATENATED MODULE: ./web/resources/menu-fluent.tsx








function menu_fluent_c(e) {
    document.body.setAttribute("data-sidebar-state", e), document.dispatchEvent(new CustomEvent("fluent-sidebar-state-change"));
}
function menu_fluent_u() {
    let e = localStorage.getItem("fluent-sidebar-state");
    return "collapsed" === e || "expanded" === e ? e : "expanded";
}
function menu_fluent_p() {
    document.querySelectorAll("#mainmenu ul.nav > li > a.menu.popup-open").forEach((e)=>{
        e.classList.remove("popup-open");
    }), document.querySelectorAll("#mainmenu ul.nav > li > ul.slide-menu.popup-open").forEach((e)=>{
        e.classList.remove("popup-open"), e.style.display = "none", e.style.top = "";
    });
}
const main = baseclass.extend({
    async __init__ () {
        let e = await ui.menu.load();
        this.render(e), setupSelectionPause(), setupErrorTooltips(), setupFluentSelects(), setupIfaceboxTooltips(), setupThemeFeatures(), setupMenuSearch(e);
    },
    render (e) {
        var t, n, a;
        let l = e, i = "", s = ui.menu.getChildren(e);
        for(let e = 0; e < s.length; e++)(L.env.requestpath.length ? s[e].name === L.env.requestpath[0] : 0 === e) && this.renderMainMenu(s[e], s[e].name);
        if (L.env.dispatchpath.length >= 3) {
            for(let e = 0; e < 3 && l; e++){
                let t = L.env.dispatchpath[e];
                l = null == (a = l.children) ? void 0 : a[t], i = i + (i ? "/" : "") + L.env.dispatchpath[e];
            }
            l && this.renderTabMenu(l, i);
        }
        let d = document.querySelectorAll("a.showSide"), r = document.querySelector(".darkMask"), o = document.querySelector(".sidebar-collapse-toggle"), m = null != (t = ui.createHandlerFn(this, "handleSidebarToggle")) ? t : ()=>{
            console.warn("Fluent menu: missing sidebar toggle handler");
        }, h = null != (n = ui.createHandlerFn(this, "handleDesktopSidebarToggle")) ? n : ()=>{
            console.warn("Fluent menu: missing desktop sidebar toggle handler");
        };
        d.forEach((e)=>{
            e.addEventListener("click", m);
        }), r && r.addEventListener("click", m), o && o.addEventListener("click", h), window.innerWidth > 768 ? menu_fluent_c(menu_fluent_u()) : document.body.setAttribute("data-sidebar-state", "expanded"), window.addEventListener("resize", ()=>{
            this.adjustBrandTextSize(), window.innerWidth > 768 ? menu_fluent_c(menu_fluent_u()) : document.body.setAttribute("data-sidebar-state", "expanded");
        }), document.addEventListener("click", (e)=>{
            if (window.innerWidth <= 768 || "collapsed" !== document.body.getAttribute("data-sidebar-state")) return;
            let t = e.target, n = document.querySelector("#mainmenu");
            t && (null == n ? void 0 : n.contains(t)) || menu_fluent_p();
        });
    },
    handleMenuExpand (e) {
        let t = e.currentTarget;
        if (!t) return;
        let n = t.parentNode, a = t.nextElementSibling, l = window.innerWidth > 768 && "collapsed" === document.body.getAttribute("data-sidebar-state"), s = !1;
        if (document.querySelectorAll(l ? ".main .main-left .nav > li > ul.slide-menu.popup-open" : ".main .main-left .nav > li > ul.slide-menu.active").forEach((e)=>{
            var t;
            s || e !== a || (s = !0), e.classList.remove("popup-open", "active"), null == (t = e.previousElementSibling) || t.classList.remove("popup-open", "active"), SlideAnimations.stop(e), l ? (e.style.display = "none", e.style.top = "") : SlideAnimations.slideUp(e, "fast");
        }), a) {
            if (!s) {
                let e = null == n ? void 0 : n.querySelector(".slide-menu");
                if (e) {
                    if (a.classList.add(l ? "popup-open" : "active"), t.classList.add(l ? "popup-open" : "active"), l) {
                        SlideAnimations.stop(e), e.style.display = "block";
                        let n = t.getBoundingClientRect(), a = e.offsetHeight, l = Math.max(8, window.innerHeight - a - 8), s = n.top - 8;
                        e.style.top = "".concat(Math.min(l, Math.max(8, s)), "px");
                    } else e.style.top = "", SlideAnimations.slideDown(e, "fast");
                    e.querySelectorAll("li > a").forEach((e)=>{
                        e.addEventListener("click", ()=>{
                            menu_fluent_p();
                        }, {
                            once: !0
                        });
                    });
                }
                t.blur();
            }
            document.dispatchEvent(new CustomEvent("fluent-menu-expand")), e.preventDefault(), e.stopPropagation();
        }
    },
    renderMainMenu (a, l, i) {
        let s = (i || 0) + 1, d = jsx("ul", {
            class: i ? "slide-menu" : "nav"
        }), r = ui.menu.getChildren(a);
        if (0 === r.length || s > 2) return jsx(Fragment, {});
        for(let n = 0; n < r.length; n++){
            let i = r[n], o = L.env.dispatchpath[s] === i.name && L.env.dispatchpath[s - 1] === a.name, c = this.renderMainMenu(i, "".concat(l, "/").concat(i.name), s), u = c.children.length > 0, p = u ? "slide" : null, m = u ? "menu" : "food";
            o && (d.classList.add("active"), p = p ? "".concat(p, " active") : "null active");
            let h = o ? "".concat(m, " active") : m, v = jsxs("li", {
                class: null != p ? p : void 0,
                children: [
                    jsxs("a", {
                        href: L.url(l, i.name),
                        onclick: 1 === s ? ui.createHandlerFn(this, "handleMenuExpand") : null,
                        class: h,
                        "data-title": (i.title || "").replace(/ /g, "_"),
                        children: [
                            1 === s || 2 === s ? jsx("span", {
                                class: "menu-icon"
                            }) : null,
                            jsx("span", {
                                class: "menu-label",
                                children: _(i.title || "")
                            })
                        ]
                    }),
                    c
                ]
            });
            d.appendChild(v);
        }
        if (1 === s) {
            let e = document.querySelector("#mainmenu");
            e && (e.appendChild(d), e.style.display = "", this.adjustBrandTextSize());
        }
        return d;
    },
    renderTabMenu (t, a, l) {
        let i = document.querySelector("#tabmenu"), s = (l || 0) + 1, d = jsx("ul", {
            class: "tabs"
        }), r = ui.menu.getChildren(t), o = null;
        if (0 === r.length) return jsx(Fragment, {});
        for(let t = 0; t < r.length; t++){
            let n = r[t], l = L.env.dispatchpath[s + 2] === n.name, i = l ? " active" : "", c = jsx("li", {
                class: "tabmenu-item-".concat(n.name).concat(i),
                children: jsx("a", {
                    href: L.url(a, n.name),
                    children: _(n.title || "")
                })
            });
            d.appendChild(c), l && (o = n);
        }
        if (i && (i.appendChild(d), i.style.display = "", o)) {
            let e = this.renderTabMenu(o, "".concat(a, "/").concat(o.name), s);
            e.children.length > 0 && i.appendChild(e);
        }
        return d;
    },
    adjustBrandTextSize () {
        let e = document.querySelector(".sidenav-header .brand-text");
        if (e) {
            let t = e.parentElement;
            if (t) {
                let n = t.clientWidth - 32;
                if (n > 0) {
                    let t = 16;
                    for(e.style.fontSize = "".concat(t, "px"); e.scrollWidth > n && t > 9;)t -= 0.5, e.style.fontSize = "".concat(t, "px");
                }
            }
        }
    },
    handleSidebarToggle (e) {
        let t = document.querySelectorAll("a.showSide"), n = document.querySelector("#mainmenu"), a = document.querySelector(".darkMask"), l = document.querySelector(".main-right");
        0 !== t.length && n && a && l ? Array.from(t).some((e)=>e.classList.contains("active")) ? (t.forEach((e)=>{
            e.classList.remove("active");
        }), n.classList.remove("active"), l.classList.remove("active"), a.classList.remove("active")) : (t.forEach((e)=>{
            e.classList.add("active");
        }), n.classList.add("active"), l.classList.add("active"), a.classList.add("active"), this.adjustBrandTextSize()) : console.warn("Fluent menu: sidebar toggle elements are unavailable");
    },
    handleDesktopSidebarToggle (e) {
        if (e.preventDefault(), e.stopPropagation(), window.innerWidth <= 768) return;
        let t = "collapsed" == ("collapsed" === document.body.getAttribute("data-sidebar-state") ? "collapsed" : "expanded") ? "expanded" : "collapsed";
        menu_fluent_p(), localStorage.setItem("fluent-sidebar-state", t), menu_fluent_c(t), "expanded" === t && this.adjustBrandTextSize();
    }
});


return main;