"use strict";
"require baseclass";
"require ui";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/animation.ts
let animation_e = L.form;
const registerAnimationTab = (n)=>{
    n.tab("animation", _("Animation"), _("Control page transitions, tab underline animation, and the top loading indicator."));
    {
        let t = n.taboption("animation", animation_e.Flag, "view_transition", _("Enable page transition animation"), _("Use the browser View Transition API to animate navigation between LuCI pages when supported."));
        t.default = t.enabled, t.rmempty = !1;
    }
    {
        let t = n.taboption("animation", animation_e.Flag, "tab_animation", _("Enable tab underline animation"), _("Animate the active underline when switching between native LuCI tabs and themed tab menus."));
        t.default = t.enabled, t.rmempty = !1;
    }
    {
        let t = n.taboption("animation", animation_e.Flag, "prefers_reduced_motion", _("Respect reduced-motion preference"), _("When enabled, Fluent animations follow the browser or operating system reduced-motion preference."));
        t.default = t.enabled, t.rmempty = !1, t.depends("tab_animation", "1");
    }
    {
        let t = n.taboption("animation", animation_e.Flag, "loading_bar", _("Show top loading bar"), _("Display the themed loading indicator at the top edge during page loads and transitions."));
        t.default = t.enabled, t.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/shared.ts
let shared_e = L.form;
const transparencySteps = [
    0,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1
];
let shared_t = "fluent-live-preview", shared_a = /(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i, shared_r = {
    primary: {
        cssVar: "--fluent-primary",
        isDark: !1
    },
    dark_primary: {
        cssVar: "--fluent-primary",
        isDark: !0
    },
    page_bg: {
        cssVar: "--fluent-bg",
        isDark: !1
    },
    dark_page_bg: {
        cssVar: "--fluent-bg",
        isDark: !0
    },
    card_bg: {
        cssVar: "--fluent-bg-card",
        isDark: !1
    },
    dark_card_bg: {
        cssVar: "--fluent-bg-card",
        isDark: !0
    },
    sidebar_bg: {
        cssVar: "--fluent-sidebar-bg",
        isDark: !1
    },
    dark_sidebar_bg: {
        cssVar: "--fluent-sidebar-bg",
        isDark: !0
    },
    progressbar_font: {
        cssVar: "--fluent-progressbar-font-color",
        isDark: !1
    },
    dark_progressbar_font: {
        cssVar: "--fluent-progressbar-font-color",
        isDark: !0
    }
}, shared_l = new globalThis.Map();
const configureHexColorValue = function(o, s) {
    let n = arguments.length > 2 && void 0 !== arguments[2] && arguments[2];
    o.rmempty = !1, o.validate = (e, t)=>!e || shared_a.test(String(t)) || _("Expecting: %s").format(_("valid HEX color value")), o.render = (c, i, u)=>{
        let d = shared_e.Value.prototype.render.call(o, c, i, u), p = ()=>{
            let e = document.querySelector('[id^="widget.cbid.fluent."][id$=".'.concat(s, '"]'));
            e && ((e, t)=>{
                if ("true" === e.dataset.fluentColorPicker) return;
                let r = e.parentElement;
                if (!r) return;
                e.dataset.fluentColorPicker = "true", e.classList.add("fluent-color-field__text");
                let l = document.createElement("div");
                l.className = "fluent-color-field";
                let o = document.createElement("label");
                o.className = "fluent-color-swatch", o.title = _("Choose color");
                let s = document.createElement("input");
                s.type = "color", s.className = "fluent-color-swatch__input", s.setAttribute("aria-label", _("Choose color"));
                let n = document.createElement("span");
                n.className = "fluent-color-swatch__preview";
                let c = (e)=>{
                    shared_a.test(e) && (s.value = e, n.style.backgroundColor = e);
                };
                c(e.value), s.addEventListener("input", ()=>{
                    e.value = s.value, n.style.backgroundColor = s.value, shared_a.test(s.value) && t(s.value);
                }), e.addEventListener("input", ()=>{
                    c(e.value), shared_a.test(e.value) && t(e.value);
                }), o.appendChild(s), o.appendChild(n), r.insertBefore(l, e), l.appendChild(e), l.appendChild(o);
            })(e, (e)=>((e, a)=>{
                    let o = shared_r[e];
                    if (!o) return;
                    let s = "".concat(o.isDark ? "dark" : "light", "|").concat(o.cssVar);
                    shared_l.set(s, {
                        selector: o.isDark ? ':root[data-theme="dark"]' : ":root",
                        cssVar: o.cssVar,
                        value: a
                    }), (()=>{
                        let e, a = ((e = document.getElementById(shared_t)) || ((e = document.createElement("style")).id = shared_t, document.head.appendChild(e)), e), r = new globalThis.Map();
                        for (let e of shared_l.values()){
                            var o;
                            let t = null != (o = r.get(e.selector)) ? o : [];
                            t.push("".concat(e.cssVar, ": ").concat(e.value, ";")), r.set(e.selector, t);
                        }
                        let s = "";
                        for (let [e, t] of r)s += "".concat(e, " { ").concat(t.join(" "), " }\n");
                        a.textContent = s;
                    })();
                })(s, e));
        };
        return n ? requestAnimationFrame(p) : setTimeout(p, 0), d;
    };
};
const createModeSubtabs = (t, a, r)=>{
    let l = t.taboption(a, shared_e.SectionValue, r, shared_e.TypedSection, "global").subsection;
    return l.anonymous = !0, l.addremove = !1, l.tab("light", _("Light mode")), l.tab("dark", _("Dark mode")), l;
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/colors.ts
let colors_e = L.form;

const registerColorsTab = (o)=>{
    o.tab("colors", _("Colors"), _("Set separate accent, progress-bar text, and background colors for light and dark mode."));
    let t = createModeSubtabs(o, "colors", "colors_mode_tabs");
    {
        let a = t.taboption("light", colors_e.Value, "primary", _("Accent color"), _("HEX color used as the primary Fluent accent when the interface is rendered in light mode."));
        a.default = "#0078d4", configureHexColorValue(a, "primary");
    }
    {
        let a = t.taboption("light", colors_e.Value, "progressbar_font", _("Progress bar text color"), _("HEX color used for progress-bar labels while the interface is rendered in light mode."));
        a.default = "#2e2b60", configureHexColorValue(a, "progressbar_font");
    }
    {
        let a = t.taboption("light", colors_e.Value, "page_bg", _("Page background"), _("HEX color used for the main page background in light mode."));
        a.default = "#fafafa", configureHexColorValue(a, "page_bg");
    }
    {
        let a = t.taboption("light", colors_e.Value, "card_bg", _("Card background"), _("HEX color used for container/card elements in light mode."));
        a.default = "#ffffff", configureHexColorValue(a, "card_bg");
    }
    {
        let a = t.taboption("light", colors_e.Value, "sidebar_bg", _("Sidebar background"), _("HEX color used for the navigation sidebar in light mode."));
        a.default = "#f3f3f3", configureHexColorValue(a, "sidebar_bg");
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_primary", _("Accent color"), _("HEX color used as the primary Fluent accent when the interface is rendered in dark mode."));
        a.default = "#4da6ff", configureHexColorValue(a, "dark_primary", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_progressbar_font", _("Progress bar text color"), _("HEX color used for progress-bar labels while the interface is rendered in dark mode."));
        a.default = "#d6d9e5", configureHexColorValue(a, "dark_progressbar_font", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_page_bg", _("Page background"), _("HEX color used for the main page background in dark mode."));
        a.default = "#1b1b1b", configureHexColorValue(a, "dark_page_bg", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_card_bg", _("Card background"), _("HEX color used for container/card elements in dark mode."));
        a.default = "#2d2d2d", configureHexColorValue(a, "dark_card_bg", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_sidebar_bg", _("Sidebar background"), _("HEX color used for the navigation sidebar in dark mode."));
        a.default = "#1f1f1f", configureHexColorValue(a, "dark_sidebar_bg", !0);
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/general.ts
let general_e = L.form;
const registerGeneralTab = (t)=>{
    t.tab("general", _("General"), _("Choose how the theme selects its mode and how large core controls should render."));
    {
        let o = t.taboption("general", general_e.ListValue, "mode", _("Color mode"));
        o.value("auto", _("Follow system")), o.value("light", _("Force light mode")), o.value("dark", _("Force dark mode")), o.default = "auto", o.rmempty = !1, o.description = _("Use the system/browser preference, or always render the Fluent theme in a fixed light or dark palette.");
    }
    {
        let o = t.taboption("general", general_e.ListValue, "font_weight", _("Navigation font weight"));
        o.value("normal", _("Normal")), o.value("600", _("Semibold")), o.default = "600", o.rmempty = !1, o.description = _("Controls the font weight used by main navigation labels and related theme text accents.");
    }
    {
        let o = t.taboption("general", general_e.ListValue, "control_height", _("Control height"));
        o.value("32", _("Compact (32px)")), o.value("42", _("Comfortable (42px)")), o.default = "32", o.rmempty = !1, o.description = _("Applies to standard buttons, inputs, selects, and similar form controls across the theme.");
    }
    {
        let o = t.taboption("general", general_e.Flag, "custom_select", _("Use Fluent custom select dropdowns"), _("Replace native select elements with the theme's custom dropdown widget."));
        o.default = o.enabled, o.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_define_property.js
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true });
    } else obj[key] = value;

    return obj;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_spread.js


function _object_spread(target) {
    for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);

        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(
                Object.getOwnPropertySymbols(source).filter(function(sym) {
                    return Object.getOwnPropertyDescriptor(source, sym).enumerable;
                })
            );
        }

        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_spread_props.js
function _object_spread_props_ownKeys(object, enumerableOnly) {
    var keys = Object.keys(object);

    if (Object.getOwnPropertySymbols) {
        var symbols = Object.getOwnPropertySymbols(object);
        if (enumerableOnly) {
            symbols = symbols.filter(function(sym) {
                return Object.getOwnPropertyDescriptor(object, sym).enumerable;
            });
        }
        keys.push.apply(keys, symbols);
    }

    return keys;
}
function _object_spread_props(target, source) {
    source = source != null ? source : {};

    if (Object.getOwnPropertyDescriptors) Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
    else {
        _object_spread_props_ownKeys(Object(source)).forEach(function(key) {
            Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key));
        });
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_without_properties_loose.js
function _object_without_properties_loose(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys = Object.getOwnPropertyNames(source), key, i;
    for (i = 0; i < sourceKeys.length; i++) {
        key = sourceKeys[i];
        if (excluded.indexOf(key) >= 0) continue;
        if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
        target[key] = source[key];
    }

    return target;
}


;// CONCATENATED MODULE: ../node_modules/.pnpm/@swc+helpers@0.5.23/node_modules/@swc/helpers/esm/_object_without_properties.js


function _object_without_properties(source, excluded) {
    if (source == null) return {};

    var target = {}, sourceKeys, key, i;
    if (typeof Reflect !== "undefined" && Reflect.ownKeys) {
        sourceKeys = Reflect.ownKeys(Object(source));
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }

        return target;
    }

    target = _object_without_properties_loose(source, excluded);
    if (Object.getOwnPropertySymbols) {
        sourceKeys = Object.getOwnPropertySymbols(source);
        for (i = 0; i < sourceKeys.length; i++) {
            key = sourceKeys[i];
            if (excluded.indexOf(key) >= 0) continue;
            if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue;
            target[key] = source[key];
        }
    }

    return target;
}



;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_6ea2f62e13eaf926b7023436bab80f34/node_modules/@lazulikao/luci-types/src/jsx/jsx-factory.ts



const Fragment = Symbol.for("jsx.fragment");
function jsx_factory_o(o, n) {
    let s = n || {}, { children: l } = s, f = _object_without_properties(s, [
        "children"
    ]), i = function e(t) {
        let r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : [];
        for (let o of t)null != o && "boolean" != typeof o && (Array.isArray(o) ? e(o, r) : r.push(o));
        return r;
    }(null == l ? [] : Array.isArray(l) ? l : [
        l
    ]);
    if (o === Fragment) {
        let e = document.createDocumentFragment();
        return e.append(...i), e;
    }
    if ("function" == typeof o) return o(_object_spread_props(_object_spread({}, f), {
        children: i
    }));
    let c = {}, p = _object_spread({}, f);
    for (let [e, t] of Object.entries(p))e.startsWith("on") && "function" == typeof t ? (c[e] = t, delete p[e]) : "boolean" == typeof t && (t ? p[e] = e : delete p[e]);
    let a = Object.keys(p).length > 0 ? i.length > 1 ? E(o, p, i) : E(o, p, i[0]) : i.length > 1 ? E(o, {}, i) : E(o, {}, i[0]);
    for (let [e, t] of Object.entries(c)){
        let r = e.slice(2).toLowerCase();
        a.addEventListener(r, t);
    }
    return a;
}
function jsx(e, t) {
    return jsx_factory_o(e, t);
}
function jsxs(e, t) {
    return jsx_factory_o(e, t);
}
function jsxDEV(e, t) {
    return jsx_factory_o(e, t);
}

;// CONCATENATED MODULE: ../node_modules/.pnpm/@lazulikao+luci-types@https_6ea2f62e13eaf926b7023436bab80f34/node_modules/@lazulikao/luci-types/src/jsx/jsx-runtime.ts


;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/login.tsx

let login_a = L.form, login_n = L.rpc, login_l = L.dom, login_o = L.fs, login_i = L.ui, login_r = login_n.declare({
    object: "luci.fluent",
    method: "avail",
    expect: {
        avail: 0
    }
}), login_c = login_n.declare({
    object: "luci.fluent",
    method: "remove",
    params: [
        "filename"
    ],
    expect: {
        result: 0
    }
}), login_d = login_n.declare({
    object: "luci.fluent",
    method: "rename",
    params: [
        "newname"
    ],
    expect: {
        result: 0
    }
});

let login_g = new Set([
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "mp4",
    "webm"
]), login_p = (e)=>{
    var t, a;
    return null != (t = null == (a = e.split(".").pop()) ? void 0 : a.toLowerCase()) ? t : "";
}, m = (e)=>login_g.has(login_p(e)), b = (e)=>e >= 1048576 ? "".concat((e / 1024 / 1024).toFixed(1), " GiB") : e >= 1024 ? "".concat((e / 1024).toFixed(1), " MiB") : "".concat(e, " KiB"), login_f = (e, t)=>{
    if (0 !== e) throw Error("".concat(t, " failed with code ").concat(e, "."));
}, h = (e, t)=>{
    login_l.content(e, t);
}, login_v = login_a.DummyValue.extend({
    renderWidget: function(a, n, l) {
        let u = jsx("div", {
            class: "cbi-value-description fluent-bg-status",
            children: "Ready to upload or remove custom backgrounds."
        }), s = jsx("div", {
            class: "fluent-bg-hint",
            children: "Supported formats: JPG, PNG, GIF, WEBP, MP4, WEBM."
        }), g = jsx("button", {
            class: "btn cbi-button cbi-button-action",
            type: "button",
            children: "Upload background"
        }), v = jsx("div", {
            class: "fluent-bg-actions",
            children: g
        }), y = jsx("div", {
            class: "fluent-bg-list"
        }), k = (e)=>{
            h(u, [
                document.createTextNode(e)
            ]);
        }, w = ()=>login_o.list("/www/luci-static/fluent/background").catch(()=>[]).then((a)=>{
                let n = a.filter((e)=>{
                    var t;
                    return "file" === e.type && m(String(null != (t = e.name) ? t : ""));
                }).sort((e, t)=>{
                    var a, n;
                    return String(null != (a = e.name) ? a : "").localeCompare(String(null != (n = t.name) ? n : ""));
                });
                n.length ? h(y, n.map((a)=>{
                    var n, l;
                    let o, r, d, u = String(null != (n = a.name) ? n : ""), s = jsx("button", {
                        class: "btn cbi-button cbi-button-remove",
                        type: "button",
                        children: "Delete"
                    }), g = login_i.createHandlerFn(this, ()=>(k("Deleting ".concat(u, "...")), login_c(u).then((e)=>(login_f(e, "Deleting ".concat(u)), w().then(()=>{
                                k("Deleted ".concat(u, "."));
                            }))).catch((e)=>{
                            k("Failed to delete ".concat(u, ": ").concat(e instanceof Error ? e.message : String(e)));
                        })));
                    return g && s.addEventListener("click", g), jsxs("div", {
                        class: "fluent-bg-item",
                        children: [
                            (o = login_p(u), r = "".concat("/luci-static/fluent/background/").concat(encodeURIComponent(u)), "mp4" === o || "webm" === o ? jsx("video", {
                                class: "fluent-bg-preview fluent-bg-preview-video",
                                muted: !0,
                                playsInline: !0,
                                preload: "metadata",
                                src: r
                            }) : jsx("div", {
                                class: "fluent-bg-preview",
                                style: "background-image:url('".concat(r.replace(/'/g, "%27"), "')")
                            })),
                            jsxs("div", {
                                class: "fluent-bg-meta",
                                children: [
                                    jsx("strong", {
                                        class: "fluent-bg-name",
                                        title: u,
                                        children: u
                                    }),
                                    jsx("span", {
                                        class: "fluent-bg-size",
                                        children: (d = Number(null != (l = a.size) ? l : 0)) > 0 ? b(Math.max(1, Math.ceil(d / 1024))) : "Unknown size"
                                    })
                                ]
                            }),
                            jsx("div", {
                                class: "fluent-bg-item-actions",
                                children: s
                            })
                        ]
                    });
                })) : h(y, jsxs("div", {
                    class: "fluent-bg-empty",
                    children: [
                        jsx("strong", {
                            children: "No custom backgrounds yet"
                        }),
                        jsx("span", {
                            children: "Upload an image or video to use it on the login page."
                        })
                    ]
                }));
            });
        return g.addEventListener("click", ()=>{
            k("Selecting background file..."), login_i.uploadFile("/tmp/fluent_background.tmp").then((e)=>{
                let t;
                if (!(null == e ? void 0 : e.name)) throw Error("Upload did not return a filename.");
                let a = "" !== (t = e.name.replace(/^.*[\\/]/, "").replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "")) && "." !== t && ".." !== t && m(t) ? t : "background-".concat(Date.now(), ".jpg");
                return k("Saving ".concat(a, "...")), login_d(a).then((e)=>(login_f(e, "Saving ".concat(a)), w().then(()=>{
                        k("Saved ".concat(a, "."));
                    }))).catch((e)=>{
                    k("Failed to save ".concat(a, ": ").concat(e instanceof Error ? e.message : String(e)));
                });
            }).catch((e)=>{
                let t = e instanceof Error ? e.message : String(e);
                t && "false" !== t ? k("Upload failed: ".concat(t)) : k("Upload canceled.");
            });
        }), login_r().then((e)=>{
            k("Ready to upload or remove custom backgrounds. Available space: ".concat(b(e), "."));
        }).catch(()=>{
            k("Ready to upload or remove custom backgrounds.");
        }), w(), jsx("div", {
            class: "fluent-bg-manager",
            children: [
                u,
                s,
                v,
                y
            ]
        });
    }
});
const registerLoginTab = (e)=>{
    e.tab("login", _("Login page"), _("Adjust login card opacity and blur separately for light and dark mode."));
    {
        let t = e.taboption("login", login_a.ListValue, "login_bg", "Background source", "Select the background image source for the login page.");
        t.value("microsoft", "Microsoft dynamic canvas"), t.value("custom", "Custom background"), t.value("bing", "Bing daily wallpaper"), t.default = "microsoft", t.rmempty = !1;
    }
    e.taboption("login", login_v, "_bg_mgr", "Custom backgrounds", "Upload and manage custom background images for the login page.").depends("login_bg", "custom");
    let t = createModeSubtabs(e, "login", "login_mode_tabs");
    {
        let e = t.taboption("light", login_a.ListValue, "transparency", _("Login card opacity"), _("Opacity of the login card in light mode. 0 is fully transparent and 1 is fully opaque."));
        for (let t of transparencySteps)e.value(String(t));
        e.default = "0.8", e.rmempty = !1;
    }
    {
        let e = t.taboption("light", login_a.Value, "blur", _("Backdrop blur radius"), _("Blur radius in pixels behind the login card in light mode. Use 0 to disable blur."));
        e.datatype = "ufloat", e.default = "20", e.rmempty = !1;
    }
    {
        let e = t.taboption("dark", login_a.ListValue, "transparency_dark", _("Login card opacity"), _("Opacity of the login card in dark mode. 0 is fully transparent and 1 is fully opaque."));
        for (let t of transparencySteps)e.value(String(t));
        e.default = "0.8", e.rmempty = !1;
    }
    {
        let e = t.taboption("dark", login_a.Value, "blur_dark", _("Backdrop blur radius"), _("Blur radius in pixels behind the login card in dark mode. Use 0 to disable blur."));
        e.datatype = "ufloat", e.default = "20", e.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config.tsx
let fluent_config_e = L.form, fluent_config_n = L.uci;




class fluent_config_i extends L.view {
    load() {
        return fluent_config_n.load("fluent");
    }
    render(n) {
        let i = new fluent_config_e.Map("fluent", _("Fluent theme settings"), _("Configure color mode, accent colors, animation behavior, and login-page appearance for luci-theme-fluent.")), l = i.section(fluent_config_e.TypedSection, "global", _("Theme settings"));
        return l.addremove = !1, l.anonymous = !0, registerGeneralTab(l), registerColorsTab(l), registerAnimationTab(l), registerLoginTab(l), i.render();
    }
}
const main = fluent_config_i;


return main;