"use strict";
"require baseclass";
"require ui";
// WARN: generated by rsbuild - do not edit

// The require scope
var __webpack_require__ = {};

// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, getters, values) => {
	var define = (defs, kind) => {
		for(var key in defs) {
			if(__webpack_require__.o(defs, key) && !__webpack_require__.o(exports, key)) {
				Object.defineProperty(exports, key, { enumerable: true, [kind]: defs[key] });
			}
		}
	};
	define(getters, "get");
	define(values, "value");
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  main: () => (/* binding */ main)
});

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/animation.ts
let animation_e = L.form;
const registerAnimationTab = (n)=>{
    n.tab("animation", _("Animation"), _("Control page transitions, tab underline animation, and the top loading indicator."));
    {
        let t = n.taboption("animation", animation_e.Flag, "view_transition", _("Enable page transition animation"), _("Use the browser View Transition API to animate navigation between LuCI pages when supported."));
        t.default = t.enabled, t.rmempty = !1;
    }
    {
        let t = n.taboption("animation", animation_e.Flag, "tab_animation", _("Enable tab underline animation"), _("Animate the active underline when switching between native LuCI tabs and themed tab menus."));
        t.default = t.enabled, t.rmempty = !1;
    }
    {
        let t = n.taboption("animation", animation_e.Flag, "prefers_reduced_motion", _("Respect reduced-motion preference"), _("When enabled, Fluent animations follow the browser or operating system reduced-motion preference."));
        t.default = t.enabled, t.rmempty = !1, t.depends("tab_animation", "1");
    }
    {
        let t = n.taboption("animation", animation_e.Flag, "loading_bar", _("Show top loading bar"), _("Display the themed loading indicator at the top edge during page loads and transitions."));
        t.default = t.enabled, t.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/shared.ts
let shared_e = L.form;
const transparencySteps = [
    0,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1
];
const configureHexColorValue = function(t, l) {
    let o = arguments.length > 2 && void 0 !== arguments[2] && arguments[2];
    t.rmempty = !1, t.validate = (e, t)=>!e || /(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i.test(String(t)) || _("Expecting: %s").format(_("valid HEX color value")), t.render = (a, r, n)=>{
        let c = shared_e.Value.prototype.render.call(t, a, r, n), i = ()=>{
            let e = document.querySelector('[id^="widget.cbid.fluent."][id$=".'.concat(l, '"]'));
            e && ((e)=>{
                if ("true" === e.dataset.fluentColorPicker) return;
                let t = e.parentElement;
                if (!t) return;
                e.dataset.fluentColorPicker = "true", e.classList.add("fluent-color-field__text");
                let l = document.createElement("div");
                l.className = "fluent-color-field";
                let o = document.createElement("label");
                o.className = "fluent-color-swatch", o.title = _("Choose color");
                let a = document.createElement("input");
                a.type = "color", a.className = "fluent-color-swatch__input", a.setAttribute("aria-label", _("Choose color"));
                let r = document.createElement("span");
                r.className = "fluent-color-swatch__preview";
                let n = (e)=>{
                    /(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i.test(e) && (a.value = e, r.style.backgroundColor = e);
                };
                n(e.value), a.addEventListener("input", ()=>{
                    e.value = a.value, r.style.backgroundColor = a.value;
                }), e.addEventListener("input", ()=>{
                    n(e.value);
                }), o.appendChild(a), o.appendChild(r), t.insertBefore(l, e), l.appendChild(e), l.appendChild(o);
            })(e);
        };
        return o ? requestAnimationFrame(i) : setTimeout(i, 0), c;
    };
};
const createModeSubtabs = (t, l, o)=>{
    let a = t.taboption(l, shared_e.SectionValue, o, shared_e.TypedSection, "global").subsection;
    return a.anonymous = !0, a.addremove = !1, a.tab("light", _("Light mode")), a.tab("dark", _("Dark mode")), a;
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/colors.ts
let colors_e = L.form;

const registerColorsTab = (o)=>{
    o.tab("colors", _("Colors"), _("Set separate accent, progress-bar text, and background colors for light and dark mode."));
    let t = createModeSubtabs(o, "colors", "colors_mode_tabs");
    {
        let a = t.taboption("light", colors_e.Value, "primary", _("Accent color"), _("HEX color used as the primary Fluent accent when the interface is rendered in light mode."));
        a.default = "#0078d4", configureHexColorValue(a, "primary");
    }
    {
        let a = t.taboption("light", colors_e.Value, "progressbar_font", _("Progress bar text color"), _("HEX color used for progress-bar labels while the interface is rendered in light mode."));
        a.default = "#2e2b60", configureHexColorValue(a, "progressbar_font");
    }
    {
        let a = t.taboption("light", colors_e.Value, "page_bg", _("Page background"), _("HEX color used for the main page background in light mode."));
        a.default = "#fafafa", configureHexColorValue(a, "page_bg");
    }
    {
        let a = t.taboption("light", colors_e.Value, "card_bg", _("Card background"), _("HEX color used for container/card elements in light mode."));
        a.default = "#ffffff", configureHexColorValue(a, "card_bg");
    }
    {
        let a = t.taboption("light", colors_e.Value, "sidebar_bg", _("Sidebar background"), _("HEX color used for the navigation sidebar in light mode."));
        a.default = "#ffffff", configureHexColorValue(a, "sidebar_bg");
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_primary", _("Accent color"), _("HEX color used as the primary Fluent accent when the interface is rendered in dark mode."));
        a.default = "#4da6ff", configureHexColorValue(a, "dark_primary", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_progressbar_font", _("Progress bar text color"), _("HEX color used for progress-bar labels while the interface is rendered in dark mode."));
        a.default = "#d6d9e5", configureHexColorValue(a, "dark_progressbar_font", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_page_bg", _("Page background"), _("HEX color used for the main page background in dark mode."));
        a.default = "#1b1b1b", configureHexColorValue(a, "dark_page_bg", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_card_bg", _("Card background"), _("HEX color used for container/card elements in dark mode."));
        a.default = "#2d2d2d", configureHexColorValue(a, "dark_card_bg", !0);
    }
    {
        let a = t.taboption("dark", colors_e.Value, "dark_sidebar_bg", _("Sidebar background"), _("HEX color used for the navigation sidebar in dark mode."));
        a.default = "#1f1f1f", configureHexColorValue(a, "dark_sidebar_bg", !0);
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/general.ts
let general_e = L.form;
const registerGeneralTab = (t)=>{
    t.tab("general", _("General"), _("Choose how the theme selects its mode and how large core controls should render."));
    {
        let o = t.taboption("general", general_e.ListValue, "mode", _("Color mode"));
        o.value("normal", _("Follow system")), o.value("light", _("Force light mode")), o.value("dark", _("Force dark mode")), o.default = "normal", o.rmempty = !1, o.description = _("Use the system/browser preference, or always render the Fluent theme in a fixed light or dark palette.");
    }
    {
        let o = t.taboption("general", general_e.ListValue, "font_weight", _("Navigation font weight"));
        o.value("normal", _("Normal")), o.value("600", _("Semibold")), o.default = "600", o.rmempty = !1, o.description = _("Controls the font weight used by main navigation labels and related theme text accents.");
    }
    {
        let o = t.taboption("general", general_e.ListValue, "control_height", _("Control height"));
        o.value("32", _("Compact (32px)")), o.value("42", _("Comfortable (42px)")), o.default = "32", o.rmempty = !1, o.description = _("Applies to standard buttons, inputs, selects, and similar form controls across the theme.");
    }
    {
        let o = t.taboption("general", general_e.Flag, "custom_select", _("Use Fluent custom select dropdowns"), _("Replace native select elements with the theme's custom dropdown widget."));
        o.default = o.enabled, o.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config/tabs/login.ts
let login_a = L.form;

const registerLoginTab = (l)=>{
    l.tab("login", _("Login page"), _("Adjust login card opacity and blur separately for light and dark mode."));
    let r = createModeSubtabs(l, "login", "login_mode_tabs");
    {
        let t = r.taboption("light", login_a.ListValue, "transparency", _("Login card opacity"), _("Opacity of the login card in light mode. 0 is fully transparent and 1 is fully opaque."));
        for (let a of transparencySteps)t.value(String(a));
        t.default = "0.5", t.rmempty = !1;
    }
    {
        let t = r.taboption("light", login_a.Value, "blur", _("Backdrop blur radius"), _("Blur radius in pixels behind the login card in light mode. Use 0 to disable blur."));
        t.datatype = "ufloat", t.default = "0", t.rmempty = !1;
    }
    {
        let t = r.taboption("dark", login_a.ListValue, "transparency_dark", _("Login card opacity"), _("Opacity of the login card in dark mode. 0 is fully transparent and 1 is fully opaque."));
        for (let a of transparencySteps)t.value(String(a));
        t.default = "0.5", t.rmempty = !1;
    }
    {
        let t = r.taboption("dark", login_a.Value, "blur_dark", _("Backdrop blur radius"), _("Blur radius in pixels behind the login card in dark mode. Use 0 to disable blur."));
        t.datatype = "ufloat", t.default = "0", t.rmempty = !1;
    }
};

;// CONCATENATED MODULE: ./web/resources/view/fluent-config.tsx
let fluent_config_e = L.form, fluent_config_n = L.uci;




class fluent_config_i extends L.view {
    load() {
        return fluent_config_n.load("fluent");
    }
    render(n) {
        let i = new fluent_config_e.Map("fluent", _("Fluent theme settings"), _("Configure color mode, accent colors, animation behavior, and login-page appearance for luci-theme-fluent.")), l = i.section(fluent_config_e.TypedSection, "global", _("Theme settings"));
        return l.addremove = !1, l.anonymous = !0, registerGeneralTab(l), registerColorsTab(l), registerAnimationTab(l), registerLoginTab(l), i.render();
    }
}
const main = fluent_config_i;


return main;