import { defineConfig, rspack } from "@rsbuild/core";
import { pluginSass } from "@rsbuild/plugin-sass";
import type { Compiler } from "@rspack/core";

const luciRequires = `"use strict";
"require baseclass";
"require ui";
// WARN: generated by rsbuild - do not edit
`;

export default defineConfig({
  environments: {
    js: {
      source: {
        entry: {
          "menu-fluent": "./web/resources/menu-fluent.tsx",
          "view/fluent-config": "./web/resources/view/fluent-config.tsx",
        },
        tsconfigPath: "./tsconfig.json",
      },
      resolve: {
        aliasStrategy: "prefer-tsconfig",
      },
      output: {
        module: true,
        charset: "ascii",
        overrideBrowserslist: ["defaults", "not ie <= 11", "not op_mini all", "chrome >= 60", "firefox >= 60", "safari >= 11", "edge >= 16"],
        distPath: {
          root: "../htdocs/luci-static/resources",
          js: ".",
        },
        filename: {
          js: "[name].js",
        },
        assetPrefix: "",
        minify: true,
        cleanDistPath: false,
      },
      tools: {
        htmlPlugin: false,
        swc: {
          jsc: {
            parser: {
              syntax: "typescript",
              tsx: true,
              decorators: true,
            },
            transform: {
              react: {
                runtime: "automatic",
                importSource: "@lazulikao/luci-types",
                useBuiltins: true,
              },
              optimizer: {
                simplify: true,
              },
            },
            minify: {
              compress: true,
              mangle: {},
            },
          },
        },
        rspack: (config) => {
          config.output = config.output || {};
          config.optimization = config.optimization || {};
          config.optimization.splitChunks = false;
          config.optimization.runtimeChunk = false;
          config.optimization.minimize = false;
          config.optimization.avoidEntryIife = true;
          config.optimization.usedExports = false;
          config.optimization.sideEffects = false;

          config.plugins = config.plugins || [];
          config.plugins.push(new rspack.BannerPlugin({ banner: luciRequires, raw: true, entryOnly: true }));
          config.plugins.push(new rspack.BannerPlugin({ banner: "return main;", raw: true, entryOnly: true, footer: true }));
          return config;
        },
      },
      performance: {
        chunkSplit: {
          strategy: "all-in-one",
        },
      },
    },
    css: {
      plugins: [pluginSass()],
      source: {
        entry: {
          fluent: "./scss/fluent.scss",
        },
      },
      output: {
        distPath: {
          root: "../htdocs/luci-static/fluent/css",
          css: ".",
          js: ".",
        },
        filename: {
          css: "[name].css",
          js: "[name].js",
        },
        cleanDistPath: true,
        charset: "ascii",
        minify: false,
        dataUriLimit: Number.MAX_SAFE_INTEGER,
      },
      tools: {
        htmlPlugin: false,
        cssLoader: {
          url: false,
        },
        rspack: (config) => {
          config.plugins = config.plugins || [];
          config.plugins.push({
            name: "RemoveEntryJsPlugin",
            apply(compiler: Compiler) {
              compiler.hooks.emit.tapAsync("RemoveEntryJsPlugin", (compilation, callback) => {
                delete compilation.assets["fluent.js"];
                delete compilation.assets["fluent.js.map"];
                callback();
              });
            },
          });
          return config;
        },
      },
    },
  },
});
